package com.model;

public class Bumen {

    private Integer bumenId;

    private String bumenName;

    private String bumenMark;

    private String bumenMark1;

    private String bumenMark2;

    private Integer bumenType;

    private Integer bumenType1;

    private Integer bumenType2;

    private Double bumenDouble;

    private Double bumenDouble1;

    private Double bumenDouble2;

    private Integer buyuanId;

    private String buyuanName;

    public Integer getBumenId() {
        return bumenId;
    }

    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    public String getBumenName() {
        return bumenName;
    }

    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    public String getBumenMark() {
        return bumenMark;
    }


    public void setBumenMark(String bumenMark) {
        this.bumenMark = bumenMark == null ? null : bumenMark.trim();
    }

    public String getBumenMark1() {
        return bumenMark1;
    }

    public void setBumenMark1(String bumenMark1) {
        this.bumenMark1 = bumenMark1 == null ? null : bumenMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bumen.bumenMark2
     *
     * @return the value of t_bumen.bumenMark2
     *
     * @mbggenerated
     */
    public String getBumenMark2() {
        return bumenMark2;
    }

    public void setBumenMark2(String bumenMark2) {
        this.bumenMark2 = bumenMark2 == null ? null : bumenMark2.trim();
    }


    public Integer getBumenType() {
        return bumenType;
    }

    public void setBumenType(Integer bumenType) {
        this.bumenType = bumenType;
    }

    public Integer getBumenType1() {
        return bumenType1;
    }

    public void setBumenType1(Integer bumenType1) {
        this.bumenType1 = bumenType1;
    }

    public Integer getBumenType2() {
        return bumenType2;
    }

    public void setBumenType2(Integer bumenType2) {
        this.bumenType2 = bumenType2;
    }

    public Double getBumenDouble() {
        return bumenDouble;
    }

    public void setBumenDouble(Double bumenDouble) {
        this.bumenDouble = bumenDouble;
    }

    public Double getBumenDouble1() {
        return bumenDouble1;
    }

    public void setBumenDouble1(Double bumenDouble1) {
        this.bumenDouble1 = bumenDouble1;
    }

    public Double getBumenDouble2() {
        return bumenDouble2;
    }

    public void setBumenDouble2(Double bumenDouble2) {
        this.bumenDouble2 = bumenDouble2;
    }

    public Integer getBuyuanId() {
        return buyuanId;
    }

    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    public String getBuyuanName() {
        return buyuanName;
    }

    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }
}