package com.model;

public class Buzhi {

    private Integer buzhiId;

    private String buzhiName;


    private String buzhiMark;

    private String buzhiMark1;

    private String buzhiMark2;

    private Integer buzhiType;

    private Integer buzhiType1;

    private Integer buzhiType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buzhi.buzhiDouble
     *
     * @mbggenerated
     */
    private Double buzhiDouble;

    private Double buzhiDouble1;

    private Double buzhiDouble2;

    private Integer buyuanId;

    private String buyuanName;

    private Integer bumenId;

    private String bumenName;

    public Integer getBuzhiId() {
        return buzhiId;
    }

    public void setBuzhiId(Integer buzhiId) {
        this.buzhiId = buzhiId;
    }

    public String getBuzhiName() {
        return buzhiName;
    }

    public void setBuzhiName(String buzhiName) {
        this.buzhiName = buzhiName == null ? null : buzhiName.trim();
    }

    public String getBuzhiMark() {
        return buzhiMark;
    }

    public void setBuzhiMark(String buzhiMark) {
        this.buzhiMark = buzhiMark == null ? null : buzhiMark.trim();
    }

    public String getBuzhiMark1() {
        return buzhiMark1;
    }

    public void setBuzhiMark1(String buzhiMark1) {
        this.buzhiMark1 = buzhiMark1 == null ? null : buzhiMark1.trim();
    }

    public String getBuzhiMark2() {
        return buzhiMark2;
    }

    public void setBuzhiMark2(String buzhiMark2) {
        this.buzhiMark2 = buzhiMark2 == null ? null : buzhiMark2.trim();
    }

    public Integer getBuzhiType() {
        return buzhiType;
    }

    public void setBuzhiType(Integer buzhiType) {
        this.buzhiType = buzhiType;
    }

    public Integer getBuzhiType1() {
        return buzhiType1;
    }

    public void setBuzhiType1(Integer buzhiType1) {
        this.buzhiType1 = buzhiType1;
    }

    public Integer getBuzhiType2() {
        return buzhiType2;
    }

    public void setBuzhiType2(Integer buzhiType2) {
        this.buzhiType2 = buzhiType2;
    }

    public Double getBuzhiDouble() {
        return buzhiDouble;
    }

    public void setBuzhiDouble(Double buzhiDouble) {
        this.buzhiDouble = buzhiDouble;
    }

    public Double getBuzhiDouble1() {
        return buzhiDouble1;
    }

    public void setBuzhiDouble1(Double buzhiDouble1) {
        this.buzhiDouble1 = buzhiDouble1;
    }

    public Double getBuzhiDouble2() {
        return buzhiDouble2;
    }

    public void setBuzhiDouble2(Double buzhiDouble2) {
        this.buzhiDouble2 = buzhiDouble2;
    }

    public Integer getBuyuanId() {
        return buyuanId;
    }

    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    public String getBuyuanName() {
        return buyuanName;
    }

    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    public Integer getBumenId() {
        return bumenId;
    }

    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    public String getBumenName() {
        return bumenName;
    }

    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }
}