package com.model;

import java.util.Date;

public class Ggpinglun {

    private Integer ggpinglunId;

    private String ggpinglunName;

    private String ggpinglunMark;

    private Date ggpinglunDate;

    private Date ggpinglunDate1;

    private Integer ggpinglunType;

    private Integer ggpinglunType1;

    private String ggpinglunImg;

    private String ggpinglunImgName;

    private Integer gonggaoId;

    private String gonggaoName;

    private Integer ggtypeId;

    private String ggtypeName;

    private Integer userId;

    private String userName;

    private Integer bumenId;

    private String bumenName;

    private Integer buyuanId;

    private String buyuanName;

    private Integer yonghuId;

    private String yonghuName;

    private Integer byumenId;

    private String byumenName;

    private Integer byuyuanId;

    private String byuyuanName;

    private Integer buzhiId;

    private String buzhiName;

    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.roleName
     *
     * @mbggenerated
     */
    private String roleName;

    private Integer byuzhiId;

    private String byuzhiName;

    private Integer yhroleId;

    private String yhroleName;

    public Integer getGgpinglunId() {
        return ggpinglunId;
    }

    public void setGgpinglunId(Integer ggpinglunId) {
        this.ggpinglunId = ggpinglunId;
    }

    public String getGgpinglunName() {
        return ggpinglunName;
    }

    public void setGgpinglunName(String ggpinglunName) {
        this.ggpinglunName = ggpinglunName == null ? null : ggpinglunName.trim();
    }
    public String getGgpinglunMark() {
        return ggpinglunMark;
    }

    public void setGgpinglunMark(String ggpinglunMark) {
        this.ggpinglunMark = ggpinglunMark == null ? null : ggpinglunMark.trim();
    }

    public Date getGgpinglunDate() {
        return ggpinglunDate;
    }

    public void setGgpinglunDate(Date ggpinglunDate) {
        this.ggpinglunDate = ggpinglunDate;
    }

    public Date getGgpinglunDate1() {
        return ggpinglunDate1;
    }

    public void setGgpinglunDate1(Date ggpinglunDate1) {
        this.ggpinglunDate1 = ggpinglunDate1;
    }

    public Integer getGgpinglunType() {
        return ggpinglunType;
    }

    public void setGgpinglunType(Integer ggpinglunType) {
        this.ggpinglunType = ggpinglunType;
    }

    public Integer getGgpinglunType1() {
        return ggpinglunType1;
    }

    public void setGgpinglunType1(Integer ggpinglunType1) {
        this.ggpinglunType1 = ggpinglunType1;
    }

    public String getGgpinglunImg() {
        return ggpinglunImg;
    }

    public void setGgpinglunImg(String ggpinglunImg) {
        this.ggpinglunImg = ggpinglunImg == null ? null : ggpinglunImg.trim();
    }

    public String getGgpinglunImgName() {
        return ggpinglunImgName;
    }

    public void setGgpinglunImgName(String ggpinglunImgName) {
        this.ggpinglunImgName = ggpinglunImgName == null ? null : ggpinglunImgName.trim();
    }

    public Integer getGonggaoId() {
        return gonggaoId;
    }

    public void setGonggaoId(Integer gonggaoId) {
        this.gonggaoId = gonggaoId;
    }

    public String getGonggaoName() {
        return gonggaoName;
    }

    public void setGonggaoName(String gonggaoName) {
        this.gonggaoName = gonggaoName == null ? null : gonggaoName.trim();
    }

    public Integer getGgtypeId() {
        return ggtypeId;
    }

    public void setGgtypeId(Integer ggtypeId) {
        this.ggtypeId = ggtypeId;
    }

    public String getGgtypeName() {
        return ggtypeName;
    }

    public void setGgtypeName(String ggtypeName) {
        this.ggtypeName = ggtypeName == null ? null : ggtypeName.trim();
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.userName
     *
     * @param userName the value for t_ggpinglun.userName
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    public Integer getBumenId() {
        return bumenId;
    }

    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    public String getBumenName() {
        return bumenName;
    }

    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    public Integer getBuyuanId() {
        return buyuanId;
    }

    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    public String getBuyuanName() {
        return buyuanName;
    }

    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    public Integer getYonghuId() {
        return yonghuId;
    }

    public void setYonghuId(Integer yonghuId) {
        this.yonghuId = yonghuId;
    }

    public String getYonghuName() {
        return yonghuName;
    }

    public void setYonghuName(String yonghuName) {
        this.yonghuName = yonghuName == null ? null : yonghuName.trim();
    }

    public Integer getByumenId() {
        return byumenId;
    }

    public void setByumenId(Integer byumenId) {
        this.byumenId = byumenId;
    }

    public String getByumenName() {
        return byumenName;
    }

    public void setByumenName(String byumenName) {
        this.byumenName = byumenName == null ? null : byumenName.trim();
    }

    public Integer getByuyuanId() {
        return byuyuanId;
    }

    public void setByuyuanId(Integer byuyuanId) {
        this.byuyuanId = byuyuanId;
    }

    public String getByuyuanName() {
        return byuyuanName;
    }

    public void setByuyuanName(String byuyuanName) {
        this.byuyuanName = byuyuanName == null ? null : byuyuanName.trim();
    }

    public Integer getBuzhiId() {
        return buzhiId;
    }

    public void setBuzhiId(Integer buzhiId) {
        this.buzhiId = buzhiId;
    }

    public String getBuzhiName() {
        return buzhiName;
    }

    public void setBuzhiName(String buzhiName) {
        this.buzhiName = buzhiName == null ? null : buzhiName.trim();
    }

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    public Integer getByuzhiId() {
        return byuzhiId;
    }

    public void setByuzhiId(Integer byuzhiId) {
        this.byuzhiId = byuzhiId;
    }

    public String getByuzhiName() {
        return byuzhiName;
    }

    public void setByuzhiName(String byuzhiName) {
        this.byuzhiName = byuzhiName == null ? null : byuzhiName.trim();
    }

    public Integer getYhroleId() {
        return yhroleId;
    }

    public void setYhroleId(Integer yhroleId) {
        this.yhroleId = yhroleId;
    }

    public String getYhroleName() {
        return yhroleName;
    }

    public void setYhroleName(String yhroleName) {
        this.yhroleName = yhroleName == null ? null : yhroleName.trim();
    }
}