package com.model;

public class Ggtype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggtype.ggtypeId
     *
     * @mbggenerated
     */
    private Integer ggtypeId;

    private String ggtypeName;

    private String ggtypeMark;

    public Integer getGgtypeId() {
        return ggtypeId;
    }

    public void setGgtypeId(Integer ggtypeId) {
        this.ggtypeId = ggtypeId;
    }

    public String getGgtypeName() {
        return ggtypeName;
    }

    public void setGgtypeName(String ggtypeName) {
        this.ggtypeName = ggtypeName == null ? null : ggtypeName.trim();
    }

    public String getGgtypeMark() {
        return ggtypeMark;
    }

    public void setGgtypeMark(String ggtypeMark) {
        this.ggtypeMark = ggtypeMark == null ? null : ggtypeMark.trim();
    }
}