package com.model;

import java.util.Date;

public class Gonggao {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gonggao.gonggaoId
     *
     * @mbggenerated
     */
    private Integer gonggaoId;

    private String gonggaoName;

    private String gonggaoMark;

    private String gonggaoImg;

    private String gonggaoImgName;

    private Date gonggaoDate;

    private Integer ggtypeId;

    private String ggtypeName;

    public Integer getGonggaoId() {
        return gonggaoId;
    }

    public void setGonggaoId(Integer gonggaoId) {
        this.gonggaoId = gonggaoId;
    }

    public String getGonggaoName() {
        return gonggaoName;
    }

    public void setGonggaoName(String gonggaoName) {
        this.gonggaoName = gonggaoName == null ? null : gonggaoName.trim();
    }

    public String getGonggaoMark() {
        return gonggaoMark;
    }

    public void setGonggaoMark(String gonggaoMark) {
        this.gonggaoMark = gonggaoMark == null ? null : gonggaoMark.trim();
    }

    public String getGonggaoImg() {
        return gonggaoImg;
    }

    public void setGonggaoImg(String gonggaoImg) {
        this.gonggaoImg = gonggaoImg == null ? null : gonggaoImg.trim();
    }

    public String getGonggaoImgName() {
        return gonggaoImgName;
    }

    public void setGonggaoImgName(String gonggaoImgName) {
        this.gonggaoImgName = gonggaoImgName == null ? null : gonggaoImgName.trim();
    }

    public Date getGonggaoDate() {
        return gonggaoDate;
    }

    public void setGonggaoDate(Date gonggaoDate) {
        this.gonggaoDate = gonggaoDate;
    }

    public Integer getGgtypeId() {
        return ggtypeId;
    }

    public void setGgtypeId(Integer ggtypeId) {
        this.ggtypeId = ggtypeId;
    }

    public String getGgtypeName() {
        return ggtypeName;
    }

    public void setGgtypeName(String ggtypeName) {
        this.ggtypeName = ggtypeName == null ? null : ggtypeName.trim();
    }
}