package com.model;

public class Jcbiaoti {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcbiaoti.jcbiaotiId
     *
     * @mbggenerated
     */
    private Integer jcbiaotiId;

    private String jcbiaotiName;

    private String jcbiaotiNeirong;

    private String jcbiaotiMark;

    private String jcbiaotiMark1;

    private String jcbiaotiMark2;

    private Integer jcbiaotiPaixu;

    private Integer jcbiaotiType;

    private Integer jcbiaotiType1;

    private Integer jcbiaotiType2;

    public Integer getJcbiaotiId() {
        return jcbiaotiId;
    }

    public void setJcbiaotiId(Integer jcbiaotiId) {
        this.jcbiaotiId = jcbiaotiId;
    }

    public String getJcbiaotiName() {
        return jcbiaotiName;
    }

    public void setJcbiaotiName(String jcbiaotiName) {
        this.jcbiaotiName = jcbiaotiName == null ? null : jcbiaotiName.trim();
    }

    public String getJcbiaotiNeirong() {
        return jcbiaotiNeirong;
    }

    public void setJcbiaotiNeirong(String jcbiaotiNeirong) {
        this.jcbiaotiNeirong = jcbiaotiNeirong == null ? null : jcbiaotiNeirong.trim();
    }

    public String getJcbiaotiMark() {
        return jcbiaotiMark;
    }

    public void setJcbiaotiMark(String jcbiaotiMark) {
        this.jcbiaotiMark = jcbiaotiMark == null ? null : jcbiaotiMark.trim();
    }

    public String getJcbiaotiMark1() {
        return jcbiaotiMark1;
    }

    public void setJcbiaotiMark1(String jcbiaotiMark1) {
        this.jcbiaotiMark1 = jcbiaotiMark1 == null ? null : jcbiaotiMark1.trim();
    }

    public String getJcbiaotiMark2() {
        return jcbiaotiMark2;
    }

    public void setJcbiaotiMark2(String jcbiaotiMark2) {
        this.jcbiaotiMark2 = jcbiaotiMark2 == null ? null : jcbiaotiMark2.trim();
    }

    public Integer getJcbiaotiPaixu() {
        return jcbiaotiPaixu;
    }

    public void setJcbiaotiPaixu(Integer jcbiaotiPaixu) {
        this.jcbiaotiPaixu = jcbiaotiPaixu;
    }

    public Integer getJcbiaotiType() {
        return jcbiaotiType;
    }

    public void setJcbiaotiType(Integer jcbiaotiType) {
        this.jcbiaotiType = jcbiaotiType;
    }

    public Integer getJcbiaotiType1() {
        return jcbiaotiType1;
    }

    public void setJcbiaotiType1(Integer jcbiaotiType1) {
        this.jcbiaotiType1 = jcbiaotiType1;
    }

    public Integer getJcbiaotiType2() {
        return jcbiaotiType2;
    }

    public void setJcbiaotiType2(Integer jcbiaotiType2) {
        this.jcbiaotiType2 = jcbiaotiType2;
    }
}