package com.model;

public class Jcdaohang {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcdaohang.jcdaohangId
     *
     * @mbggenerated
     */
    private Integer jcdaohangId;

    private String jcdaohangName;

    private String jcdaohangNeirong;

    private String jcdaohangMark;

    private String jcdaohangMark1;

    private String jcdaohangMark2;

    private Integer jcdaohangPaixu;

    private Integer jcdaohangType;

    private Integer jcdaohangType1;

    private Integer jcdaohangType2;

    private Integer jcbiaotiId;

    private String jcbiaotiName;

    public Integer getJcdaohangId() {
        return jcdaohangId;
    }

    public void setJcdaohangId(Integer jcdaohangId) {
        this.jcdaohangId = jcdaohangId;
    }

    public String getJcdaohangName() {
        return jcdaohangName;
    }

    public void setJcdaohangName(String jcdaohangName) {
        this.jcdaohangName = jcdaohangName == null ? null : jcdaohangName.trim();
    }

    public String getJcdaohangNeirong() {
        return jcdaohangNeirong;
    }

    public void setJcdaohangNeirong(String jcdaohangNeirong) {
        this.jcdaohangNeirong = jcdaohangNeirong == null ? null : jcdaohangNeirong.trim();
    }

    public String getJcdaohangMark() {
        return jcdaohangMark;
    }

    public void setJcdaohangMark(String jcdaohangMark) {
        this.jcdaohangMark = jcdaohangMark == null ? null : jcdaohangMark.trim();
    }

    public String getJcdaohangMark1() {
        return jcdaohangMark1;
    }

    public void setJcdaohangMark1(String jcdaohangMark1) {
        this.jcdaohangMark1 = jcdaohangMark1 == null ? null : jcdaohangMark1.trim();
    }

    public String getJcdaohangMark2() {
        return jcdaohangMark2;
    }

    public void setJcdaohangMark2(String jcdaohangMark2) {
        this.jcdaohangMark2 = jcdaohangMark2 == null ? null : jcdaohangMark2.trim();
    }

    public Integer getJcdaohangPaixu() {
        return jcdaohangPaixu;
    }

    public void setJcdaohangPaixu(Integer jcdaohangPaixu) {
        this.jcdaohangPaixu = jcdaohangPaixu;
    }

    public Integer getJcdaohangType() {
        return jcdaohangType;
    }

    public void setJcdaohangType(Integer jcdaohangType) {
        this.jcdaohangType = jcdaohangType;
    }

    public Integer getJcdaohangType1() {
        return jcdaohangType1;
    }

    public void setJcdaohangType1(Integer jcdaohangType1) {
        this.jcdaohangType1 = jcdaohangType1;
    }

    public Integer getJcdaohangType2() {
        return jcdaohangType2;
    }

    public void setJcdaohangType2(Integer jcdaohangType2) {
        this.jcdaohangType2 = jcdaohangType2;
    }

    public Integer getJcbiaotiId() {
        return jcbiaotiId;
    }

    public void setJcbiaotiId(Integer jcbiaotiId) {
        this.jcbiaotiId = jcbiaotiId;
    }

    public String getJcbiaotiName() {
        return jcbiaotiName;
    }

    public void setJcbiaotiName(String jcbiaotiName) {
        this.jcbiaotiName = jcbiaotiName == null ? null : jcbiaotiName.trim();
    }
}