package com.model;

public class Jcpeizhi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.jcpeizhiId
     *
     * @mbggenerated
     */
    private Integer jcpeizhiId;

    private String jcpeizhiName;

    private String jcpeizhiNeirong;

    private String jcpeizhiMark;

    private String bumenBieming;

    private String buyuanBieming;

    private String buzhiBieming;

    private String userBieming;

    private String uxtypeBieming;

    private String uxinxiBieming;

    private String uyijianBieming;

    private String roleBieming;

    private String byumenBieming;

    private String byuyuanBieming;

    private String byuzhiBieming;

    private String yonghuBieming;

    private String yxtypeBieming;

    private String yxinxiBieming;

    private String yyijianBieming;

    private String yhroleBieming;

    private String ggtypeBieming;

    private String gonggaoBieming;

    private String ggpinglunBieming;

    private String shujuBieming;

    private String sjduochuBieming;

    private String sjjianchuBieming;

    private String sjlaiyuanBieming;

    private String sjleixingBieming;

    private String sjpinglunBieming;

    private String sjqitaBieming;

    private String sjshaochuBieming;

    private String sjxingtaiBieming;

    private Integer jcpeizhiType;

    private Integer jcpeizhiType1;

    private Integer jcpeizhiType2;

    public Integer getJcpeizhiId() {
        return jcpeizhiId;
    }

    public void setJcpeizhiId(Integer jcpeizhiId) {
        this.jcpeizhiId = jcpeizhiId;
    }

    public String getJcpeizhiName() {
        return jcpeizhiName;
    }

    public void setJcpeizhiName(String jcpeizhiName) {
        this.jcpeizhiName = jcpeizhiName == null ? null : jcpeizhiName.trim();
    }

    public String getJcpeizhiNeirong() {
        return jcpeizhiNeirong;
    }

    public void setJcpeizhiNeirong(String jcpeizhiNeirong) {
        this.jcpeizhiNeirong = jcpeizhiNeirong == null ? null : jcpeizhiNeirong.trim();
    }

    public String getJcpeizhiMark() {
        return jcpeizhiMark;
    }

    public void setJcpeizhiMark(String jcpeizhiMark) {
        this.jcpeizhiMark = jcpeizhiMark == null ? null : jcpeizhiMark.trim();
    }

    public String getBumenBieming() {
        return bumenBieming;
    }

    public void setBumenBieming(String bumenBieming) {
        this.bumenBieming = bumenBieming == null ? null : bumenBieming.trim();
    }

    public String getBuyuanBieming() {
        return buyuanBieming;
    }

    public void setBuyuanBieming(String buyuanBieming) {
        this.buyuanBieming = buyuanBieming == null ? null : buyuanBieming.trim();
    }

    public String getBuzhiBieming() {
        return buzhiBieming;
    }

    public void setBuzhiBieming(String buzhiBieming) {
        this.buzhiBieming = buzhiBieming == null ? null : buzhiBieming.trim();
    }

    public String getUserBieming() {
        return userBieming;
    }

    public void setUserBieming(String userBieming) {
        this.userBieming = userBieming == null ? null : userBieming.trim();
    }

    public String getUxtypeBieming() {
        return uxtypeBieming;
    }

    public void setUxtypeBieming(String uxtypeBieming) {
        this.uxtypeBieming = uxtypeBieming == null ? null : uxtypeBieming.trim();
    }

    public String getUxinxiBieming() {
        return uxinxiBieming;
    }

    public void setUxinxiBieming(String uxinxiBieming) {
        this.uxinxiBieming = uxinxiBieming == null ? null : uxinxiBieming.trim();
    }

    public String getUyijianBieming() {
        return uyijianBieming;
    }

    public void setUyijianBieming(String uyijianBieming) {
        this.uyijianBieming = uyijianBieming == null ? null : uyijianBieming.trim();
    }

    public String getRoleBieming() {
        return roleBieming;
    }

    public void setRoleBieming(String roleBieming) {
        this.roleBieming = roleBieming == null ? null : roleBieming.trim();
    }

    public String getByumenBieming() {
        return byumenBieming;
    }

    public void setByumenBieming(String byumenBieming) {
        this.byumenBieming = byumenBieming == null ? null : byumenBieming.trim();
    }

    public String getByuyuanBieming() {
        return byuyuanBieming;
    }

    public void setByuyuanBieming(String byuyuanBieming) {
        this.byuyuanBieming = byuyuanBieming == null ? null : byuyuanBieming.trim();
    }

    public String getByuzhiBieming() {
        return byuzhiBieming;
    }

    public void setByuzhiBieming(String byuzhiBieming) {
        this.byuzhiBieming = byuzhiBieming == null ? null : byuzhiBieming.trim();
    }

    public String getYonghuBieming() {
        return yonghuBieming;
    }

    public void setYonghuBieming(String yonghuBieming) {
        this.yonghuBieming = yonghuBieming == null ? null : yonghuBieming.trim();
    }

    public String getYxtypeBieming() {
        return yxtypeBieming;
    }

    public void setYxtypeBieming(String yxtypeBieming) {
        this.yxtypeBieming = yxtypeBieming == null ? null : yxtypeBieming.trim();
    }

    public String getYxinxiBieming() {
        return yxinxiBieming;
    }

    public void setYxinxiBieming(String yxinxiBieming) {
        this.yxinxiBieming = yxinxiBieming == null ? null : yxinxiBieming.trim();
    }

    public String getYyijianBieming() {
        return yyijianBieming;
    }

    public void setYyijianBieming(String yyijianBieming) {
        this.yyijianBieming = yyijianBieming == null ? null : yyijianBieming.trim();
    }

    public String getYhroleBieming() {
        return yhroleBieming;
    }

    public void setYhroleBieming(String yhroleBieming) {
        this.yhroleBieming = yhroleBieming == null ? null : yhroleBieming.trim();
    }

    public String getGgtypeBieming() {
        return ggtypeBieming;
    }

    public void setGgtypeBieming(String ggtypeBieming) {
        this.ggtypeBieming = ggtypeBieming == null ? null : ggtypeBieming.trim();
    }

    public String getGonggaoBieming() {
        return gonggaoBieming;
    }

    public void setGonggaoBieming(String gonggaoBieming) {
        this.gonggaoBieming = gonggaoBieming == null ? null : gonggaoBieming.trim();
    }

    public String getGgpinglunBieming() {
        return ggpinglunBieming;
    }

    public void setGgpinglunBieming(String ggpinglunBieming) {
        this.ggpinglunBieming = ggpinglunBieming == null ? null : ggpinglunBieming.trim();
    }

    public String getShujuBieming() {
        return shujuBieming;
    }

    public void setShujuBieming(String shujuBieming) {
        this.shujuBieming = shujuBieming == null ? null : shujuBieming.trim();
    }

    public String getSjduochuBieming() {
        return sjduochuBieming;
    }

    public void setSjduochuBieming(String sjduochuBieming) {
        this.sjduochuBieming = sjduochuBieming == null ? null : sjduochuBieming.trim();
    }

    public String getSjjianchuBieming() {
        return sjjianchuBieming;
    }

    public void setSjjianchuBieming(String sjjianchuBieming) {
        this.sjjianchuBieming = sjjianchuBieming == null ? null : sjjianchuBieming.trim();
    }

    public String getSjlaiyuanBieming() {
        return sjlaiyuanBieming;
    }

    public void setSjlaiyuanBieming(String sjlaiyuanBieming) {
        this.sjlaiyuanBieming = sjlaiyuanBieming == null ? null : sjlaiyuanBieming.trim();
    }

    public String getSjleixingBieming() {
        return sjleixingBieming;
    }

    public void setSjleixingBieming(String sjleixingBieming) {
        this.sjleixingBieming = sjleixingBieming == null ? null : sjleixingBieming.trim();
    }

    public String getSjpinglunBieming() {
        return sjpinglunBieming;
    }

    public void setSjpinglunBieming(String sjpinglunBieming) {
        this.sjpinglunBieming = sjpinglunBieming == null ? null : sjpinglunBieming.trim();
    }

    public String getSjqitaBieming() {
        return sjqitaBieming;
    }

    public void setSjqitaBieming(String sjqitaBieming) {
        this.sjqitaBieming = sjqitaBieming == null ? null : sjqitaBieming.trim();
    }

    public String getSjshaochuBieming() {
        return sjshaochuBieming;
    }

    public void setSjshaochuBieming(String sjshaochuBieming) {
        this.sjshaochuBieming = sjshaochuBieming == null ? null : sjshaochuBieming.trim();
    }

    public String getSjxingtaiBieming() {
        return sjxingtaiBieming;
    }

    public void setSjxingtaiBieming(String sjxingtaiBieming) {
        this.sjxingtaiBieming = sjxingtaiBieming == null ? null : sjxingtaiBieming.trim();
    }

    public Integer getJcpeizhiType() {
        return jcpeizhiType;
    }

    public void setJcpeizhiType(Integer jcpeizhiType) {
        this.jcpeizhiType = jcpeizhiType;
    }

    public Integer getJcpeizhiType1() {
        return jcpeizhiType1;
    }

    public void setJcpeizhiType1(Integer jcpeizhiType1) {
        this.jcpeizhiType1 = jcpeizhiType1;
    }

    public Integer getJcpeizhiType2() {
        return jcpeizhiType2;
    }

    public void setJcpeizhiType2(Integer jcpeizhiType2) {
        this.jcpeizhiType2 = jcpeizhiType2;
    }
}