package com.model;

import java.util.Date;

public class Rizhi {

    private Integer rizhiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rizhi.rizhiName
     *
     * @mbggenerated
     */
    private String rizhiName;

    private String dengluIp;

    private Date date;

    public Integer getRizhiId() {
        return rizhiId;
    }

    public void setRizhiId(Integer rizhiId) {
        this.rizhiId = rizhiId;
    }

    public String getRizhiName() {
        return rizhiName;
    }

    public void setRizhiName(String rizhiName) {
        this.rizhiName = rizhiName == null ? null : rizhiName.trim();
    }

    public String getDengluIp() {
        return dengluIp;
    }

    public void setDengluIp(String dengluIp) {
        this.dengluIp = dengluIp == null ? null : dengluIp.trim();
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }
}