package com.model;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.roleId
     *
     * @mbggenerated
     */
    private Integer roleId;

    private String roleName;

    private String roleMark;

    private String roleMark1;

    private Integer roleMark2;

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    public String getRoleMark() {
        return roleMark;
    }

    public void setRoleMark(String roleMark) {
        this.roleMark = roleMark == null ? null : roleMark.trim();
    }

    public String getRoleMark1() {
        return roleMark1;
    }

    public void setRoleMark1(String roleMark1) {
        this.roleMark1 = roleMark1 == null ? null : roleMark1.trim();
    }

    public Integer getRoleMark2() {
        return roleMark2;
    }

    public void setRoleMark2(Integer roleMark2) {
        this.roleMark2 = roleMark2;
    }
}