package com.model;

import java.util.Date;

public class Shuju {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuId
     *
     * @mbggenerated
     */
    private Integer shujuId;

    private String shujuName;

    private String shujuMark;

    private String shujuMark1;

    private String shujuMark2;

    private String shujuMark3;

    private Date shujuDate;

    private Date shujuDate1;

    private Integer shujuZong;

    private Integer shujuZong1;

    private Integer shujuZong2;

    private Double shujuDouble;

    private Double shujuDouble1;

    private Double shujuDouble2;

    private Double shujuDouble3;

    private Double shujuDouble4;

    private Integer shujuType;

    private Integer shujuType1;

    private Integer shujuType2;

    private String shujuImg;

    private String shujuImgName;

    private Integer sjleixingId;

    private String sjleixingName;

    private Integer sjxingtaiId;

    private String sjxingtaiName;

    private Integer userId;

    private String userName;

    private Integer bumenId;

    private String bumenName;

    private Integer buyuanId;

    private String buyuanName;

    private Integer yonghuId;

    private String yonghuName;

    private Integer byumenId;

    private String byumenName;

    private Integer byuyuanId;

    private String byuyuanName;

    private Integer buzhiId;

    private String buzhiName;

    private Integer roleId;

    private String roleName;

    private Integer byuzhiId;

    private String byuzhiName;

    private Integer yhroleId;

    private String yhroleName;


    public Integer getShujuId() {
        return shujuId;
    }

    public void setShujuId(Integer shujuId) {
        this.shujuId = shujuId;
    }

    public String getShujuName() {
        return shujuName;
    }

    public void setShujuName(String shujuName) {
        this.shujuName = shujuName == null ? null : shujuName.trim();
    }

    public String getShujuMark() {
        return shujuMark;
    }

    public void setShujuMark(String shujuMark) {
        this.shujuMark = shujuMark == null ? null : shujuMark.trim();
    }

    public String getShujuMark1() {
        return shujuMark1;
    }

    public void setShujuMark1(String shujuMark1) {
        this.shujuMark1 = shujuMark1 == null ? null : shujuMark1.trim();
    }

    public String getShujuMark2() {
        return shujuMark2;
    }

    public void setShujuMark2(String shujuMark2) {
        this.shujuMark2 = shujuMark2 == null ? null : shujuMark2.trim();
    }

    public String getShujuMark3() {
        return shujuMark3;
    }

    public void setShujuMark3(String shujuMark3) {
        this.shujuMark3 = shujuMark3 == null ? null : shujuMark3.trim();
    }

    public Date getShujuDate() {
        return shujuDate;
    }

    public void setShujuDate(Date shujuDate) {
        this.shujuDate = shujuDate;
    }

    public Date getShujuDate1() {
        return shujuDate1;
    }

    public void setShujuDate1(Date shujuDate1) {
        this.shujuDate1 = shujuDate1;
    }

    public Integer getShujuZong() {
        return shujuZong;
    }

    public void setShujuZong(Integer shujuZong) {
        this.shujuZong = shujuZong;
    }

    public Integer getShujuZong1() {
        return shujuZong1;
    }

    public void setShujuZong1(Integer shujuZong1) {
        this.shujuZong1 = shujuZong1;
    }

    public Integer getShujuZong2() {
        return shujuZong2;
    }

    public void setShujuZong2(Integer shujuZong2) {
        this.shujuZong2 = shujuZong2;
    }

    public Double getShujuDouble() {
        return shujuDouble;
    }

    public void setShujuDouble(Double shujuDouble) {
        this.shujuDouble = shujuDouble;
    }

    public Double getShujuDouble1() {
        return shujuDouble1;
    }

    public void setShujuDouble1(Double shujuDouble1) {
        this.shujuDouble1 = shujuDouble1;
    }

    public Double getShujuDouble2() {
        return shujuDouble2;
    }

    public void setShujuDouble2(Double shujuDouble2) {
        this.shujuDouble2 = shujuDouble2;
    }

    public Double getShujuDouble3() {
        return shujuDouble3;
    }

    public void setShujuDouble3(Double shujuDouble3) {
        this.shujuDouble3 = shujuDouble3;
    }

    public Double getShujuDouble4() {
        return shujuDouble4;
    }

    public void setShujuDouble4(Double shujuDouble4) {
        this.shujuDouble4 = shujuDouble4;
    }

    public Integer getShujuType() {
        return shujuType;
    }

    public void setShujuType(Integer shujuType) {
        this.shujuType = shujuType;
    }

    public Integer getShujuType1() {
        return shujuType1;
    }

    public void setShujuType1(Integer shujuType1) {
        this.shujuType1 = shujuType1;
    }

    public Integer getShujuType2() {
        return shujuType2;
    }

    public void setShujuType2(Integer shujuType2) {
        this.shujuType2 = shujuType2;
    }

    public String getShujuImg() {
        return shujuImg;
    }

    public void setShujuImg(String shujuImg) {
        this.shujuImg = shujuImg == null ? null : shujuImg.trim();
    }

    public String getShujuImgName() {
        return shujuImgName;
    }

    public void setShujuImgName(String shujuImgName) {
        this.shujuImgName = shujuImgName == null ? null : shujuImgName.trim();
    }

    public Integer getSjleixingId() {
        return sjleixingId;
    }

    public void setSjleixingId(Integer sjleixingId) {
        this.sjleixingId = sjleixingId;
    }

    public String getSjleixingName() {
        return sjleixingName;
    }

    public void setSjleixingName(String sjleixingName) {
        this.sjleixingName = sjleixingName == null ? null : sjleixingName.trim();
    }

    public Integer getSjxingtaiId() {
        return sjxingtaiId;
    }

    public void setSjxingtaiId(Integer sjxingtaiId) {
        this.sjxingtaiId = sjxingtaiId;
    }

    public String getSjxingtaiName() {
        return sjxingtaiName;
    }

    public void setSjxingtaiName(String sjxingtaiName) {
        this.sjxingtaiName = sjxingtaiName == null ? null : sjxingtaiName.trim();
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    public Integer getBumenId() {
        return bumenId;
    }

    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    public String getBumenName() {
        return bumenName;
    }

    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    public Integer getBuyuanId() {
        return buyuanId;
    }

    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    public String getBuyuanName() {
        return buyuanName;
    }

    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    public Integer getYonghuId() {
        return yonghuId;
    }

    public void setYonghuId(Integer yonghuId) {
        this.yonghuId = yonghuId;
    }

    public String getYonghuName() {
        return yonghuName;
    }

    public void setYonghuName(String yonghuName) {
        this.yonghuName = yonghuName == null ? null : yonghuName.trim();
    }

    public Integer getByumenId() {
        return byumenId;
    }

    public void setByumenId(Integer byumenId) {
        this.byumenId = byumenId;
    }

    public String getByumenName() {
        return byumenName;
    }

    public void setByumenName(String byumenName) {
        this.byumenName = byumenName == null ? null : byumenName.trim();
    }

    public Integer getByuyuanId() {
        return byuyuanId;
    }

    public void setByuyuanId(Integer byuyuanId) {
        this.byuyuanId = byuyuanId;
    }

    public String getByuyuanName() {
        return byuyuanName;
    }

    public void setByuyuanName(String byuyuanName) {
        this.byuyuanName = byuyuanName == null ? null : byuyuanName.trim();
    }

    public Integer getBuzhiId() {
        return buzhiId;
    }

    public void setBuzhiId(Integer buzhiId) {
        this.buzhiId = buzhiId;
    }

    public String getBuzhiName() {
        return buzhiName;
    }

    public void setBuzhiName(String buzhiName) {
        this.buzhiName = buzhiName == null ? null : buzhiName.trim();
    }

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    public Integer getByuzhiId() {
        return byuzhiId;
    }

    public void setByuzhiId(Integer byuzhiId) {
        this.byuzhiId = byuzhiId;
    }

    public String getByuzhiName() {
        return byuzhiName;
    }

    public void setByuzhiName(String byuzhiName) {
        this.byuzhiName = byuzhiName == null ? null : byuzhiName.trim();
    }

    public Integer getYhroleId() {
        return yhroleId;
    }

    public void setYhroleId(Integer yhroleId) {
        this.yhroleId = yhroleId;
    }

    public String getYhroleName() {
        return yhroleName;
    }

    public void setYhroleName(String yhroleName) {
        this.yhroleName = yhroleName == null ? null : yhroleName.trim();
    }
}