package com.model;

import java.util.Date;

public class Sjduochu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuId
     *
     * @mbggenerated
     */
    private Integer sjduochuId;

    private String sjduochuName;

    private String sjduochuMark;

    private String sjduochuMark1;

    private String sjduochuMark2;

    private String sjduochuMark3;

    private Date sjduochuDate;

    private Date sjduochuDate1;

    private Integer sjduochuZong;

    private Integer sjduochuZong1;

    private Integer sjduochuZong2;

    private Double sjduochuDouble;

    private Double sjduochuDouble1;

    private Double sjduochuDouble2;

    private Integer sjduochuType;

    private Integer sjduochuType1;

    private Integer sjduochuType2;

    private Integer sjqitaId;

    private String sjqitaName;

    private Integer sjlaiyuanId;

    private String sjlaiyuanName;

    private String sjduochuImg;

    private String sjduochuImgName;

    private Integer shujuId;

    private String shujuName;

    private Integer sjleixingId;

    private String sjleixingName;

    private Integer sjxingtaiId;

    private String sjxingtaiName;

    private Integer userId;

    private String userName;

    private Integer bumenId;

    private String bumenName;

    private Integer buyuanId;

    private String buyuanName;

    private Integer yonghuId;

    private String yonghuName;

    private Integer byumenId;

    private String byumenName;

    private Integer byuyuanId;

    private String byuyuanName;

    private Integer buzhiId;

    private String buzhiName;

    private Integer roleId;

    private String roleName;

    private Integer byuzhiId;

    private String byuzhiName;

    private Integer yhroleId;

    private String yhroleName;

    public Integer getSjduochuId() {
        return sjduochuId;
    }

    public void setSjduochuId(Integer sjduochuId) {
        this.sjduochuId = sjduochuId;
    }

    public String getSjduochuName() {
        return sjduochuName;
    }

    public void setSjduochuName(String sjduochuName) {
        this.sjduochuName = sjduochuName == null ? null : sjduochuName.trim();
    }

    public String getSjduochuMark() {
        return sjduochuMark;
    }

    public void setSjduochuMark(String sjduochuMark) {
        this.sjduochuMark = sjduochuMark == null ? null : sjduochuMark.trim();
    }

    public String getSjduochuMark1() {
        return sjduochuMark1;
    }

    public void setSjduochuMark1(String sjduochuMark1) {
        this.sjduochuMark1 = sjduochuMark1 == null ? null : sjduochuMark1.trim();
    }

    public String getSjduochuMark2() {
        return sjduochuMark2;
    }

    public void setSjduochuMark2(String sjduochuMark2) {
        this.sjduochuMark2 = sjduochuMark2 == null ? null : sjduochuMark2.trim();
    }

    public String getSjduochuMark3() {
        return sjduochuMark3;
    }

    public void setSjduochuMark3(String sjduochuMark3) {
        this.sjduochuMark3 = sjduochuMark3 == null ? null : sjduochuMark3.trim();
    }

    public Date getSjduochuDate() {
        return sjduochuDate;
    }

    public void setSjduochuDate(Date sjduochuDate) {
        this.sjduochuDate = sjduochuDate;
    }

    public Date getSjduochuDate1() {
        return sjduochuDate1;
    }

    public void setSjduochuDate1(Date sjduochuDate1) {
        this.sjduochuDate1 = sjduochuDate1;
    }

    public Integer getSjduochuZong() {
        return sjduochuZong;
    }

    public void setSjduochuZong(Integer sjduochuZong) {
        this.sjduochuZong = sjduochuZong;
    }

    public Integer getSjduochuZong1() {
        return sjduochuZong1;
    }

    public void setSjduochuZong1(Integer sjduochuZong1) {
        this.sjduochuZong1 = sjduochuZong1;
    }

    public Integer getSjduochuZong2() {
        return sjduochuZong2;
    }

    public void setSjduochuZong2(Integer sjduochuZong2) {
        this.sjduochuZong2 = sjduochuZong2;
    }

    public Double getSjduochuDouble() {
        return sjduochuDouble;
    }

    public void setSjduochuDouble(Double sjduochuDouble) {
        this.sjduochuDouble = sjduochuDouble;
    }

    public Double getSjduochuDouble1() {
        return sjduochuDouble1;
    }

    public void setSjduochuDouble1(Double sjduochuDouble1) {
        this.sjduochuDouble1 = sjduochuDouble1;
    }

    public Double getSjduochuDouble2() {
        return sjduochuDouble2;
    }

    public void setSjduochuDouble2(Double sjduochuDouble2) {
        this.sjduochuDouble2 = sjduochuDouble2;
    }

    public Integer getSjduochuType() {
        return sjduochuType;
    }

    public void setSjduochuType(Integer sjduochuType) {
        this.sjduochuType = sjduochuType;
    }

    public Integer getSjduochuType1() {
        return sjduochuType1;
    }

    public void setSjduochuType1(Integer sjduochuType1) {
        this.sjduochuType1 = sjduochuType1;
    }

    public Integer getSjduochuType2() {
        return sjduochuType2;
    }

    public void setSjduochuType2(Integer sjduochuType2) {
        this.sjduochuType2 = sjduochuType2;
    }

    public Integer getSjqitaId() {
        return sjqitaId;
    }

    public void setSjqitaId(Integer sjqitaId) {
        this.sjqitaId = sjqitaId;
    }

    public String getSjqitaName() {
        return sjqitaName;
    }

    public void setSjqitaName(String sjqitaName) {
        this.sjqitaName = sjqitaName == null ? null : sjqitaName.trim();
    }

    public Integer getSjlaiyuanId() {
        return sjlaiyuanId;
    }

    public void setSjlaiyuanId(Integer sjlaiyuanId) {
        this.sjlaiyuanId = sjlaiyuanId;
    }

    public String getSjlaiyuanName() {
        return sjlaiyuanName;
    }

    public void setSjlaiyuanName(String sjlaiyuanName) {
        this.sjlaiyuanName = sjlaiyuanName == null ? null : sjlaiyuanName.trim();
    }

    public String getSjduochuImg() {
        return sjduochuImg;
    }

    public void setSjduochuImg(String sjduochuImg) {
        this.sjduochuImg = sjduochuImg == null ? null : sjduochuImg.trim();
    }

    public String getSjduochuImgName() {
        return sjduochuImgName;
    }

    public void setSjduochuImgName(String sjduochuImgName) {
        this.sjduochuImgName = sjduochuImgName == null ? null : sjduochuImgName.trim();
    }

    public Integer getShujuId() {
        return shujuId;
    }

    public void setShujuId(Integer shujuId) {
        this.shujuId = shujuId;
    }

    public String getShujuName() {
        return shujuName;
    }

    public void setShujuName(String shujuName) {
        this.shujuName = shujuName == null ? null : shujuName.trim();
    }

    public Integer getSjleixingId() {
        return sjleixingId;
    }

    public void setSjleixingId(Integer sjleixingId) {
        this.sjleixingId = sjleixingId;
    }

    public String getSjleixingName() {
        return sjleixingName;
    }

    public void setSjleixingName(String sjleixingName) {
        this.sjleixingName = sjleixingName == null ? null : sjleixingName.trim();
    }

    public Integer getSjxingtaiId() {
        return sjxingtaiId;
    }

    public void setSjxingtaiId(Integer sjxingtaiId) {
        this.sjxingtaiId = sjxingtaiId;
    }

    public String getSjxingtaiName() {
        return sjxingtaiName;
    }

    public void setSjxingtaiName(String sjxingtaiName) {
        this.sjxingtaiName = sjxingtaiName == null ? null : sjxingtaiName.trim();
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    public Integer getBumenId() {
        return bumenId;
    }

    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    public String getBumenName() {
        return bumenName;
    }

    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    public Integer getBuyuanId() {
        return buyuanId;
    }

    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    public String getBuyuanName() {
        return buyuanName;
    }

    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    public Integer getYonghuId() {
        return yonghuId;
    }

    public void setYonghuId(Integer yonghuId) {
        this.yonghuId = yonghuId;
    }

    public String getYonghuName() {
        return yonghuName;
    }

    public void setYonghuName(String yonghuName) {
        this.yonghuName = yonghuName == null ? null : yonghuName.trim();
    }

    public Integer getByumenId() {
        return byumenId;
    }

    public void setByumenId(Integer byumenId) {
        this.byumenId = byumenId;
    }

    public String getByumenName() {
        return byumenName;
    }

    public void setByumenName(String byumenName) {
        this.byumenName = byumenName == null ? null : byumenName.trim();
    }

    public Integer getByuyuanId() {
        return byuyuanId;
    }

    public void setByuyuanId(Integer byuyuanId) {
        this.byuyuanId = byuyuanId;
    }

    public String getByuyuanName() {
        return byuyuanName;
    }

    public void setByuyuanName(String byuyuanName) {
        this.byuyuanName = byuyuanName == null ? null : byuyuanName.trim();
    }

    public Integer getBuzhiId() {
        return buzhiId;
    }

    public void setBuzhiId(Integer buzhiId) {
        this.buzhiId = buzhiId;
    }

    public String getBuzhiName() {
        return buzhiName;
    }

    public void setBuzhiName(String buzhiName) {
        this.buzhiName = buzhiName == null ? null : buzhiName.trim();
    }

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    public Integer getByuzhiId() {
        return byuzhiId;
    }

    public void setByuzhiId(Integer byuzhiId) {
        this.byuzhiId = byuzhiId;
    }

    public String getByuzhiName() {
        return byuzhiName;
    }

    public void setByuzhiName(String byuzhiName) {
        this.byuzhiName = byuzhiName == null ? null : byuzhiName.trim();
    }

    public Integer getYhroleId() {
        return yhroleId;
    }

    public void setYhroleId(Integer yhroleId) {
        this.yhroleId = yhroleId;
    }

    public String getYhroleName() {
        return yhroleName;
    }

    public void setYhroleName(String yhroleName) {
        this.yhroleName = yhroleName == null ? null : yhroleName.trim();
    }
}