package com.model;

import java.util.Date;

public class Sjjianchu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuId
     *
     * @mbggenerated
     */
    private Integer sjjianchuId;

    private String sjjianchuName;

    private String sjjianchuMark;

    private String sjjianchuMark1;

    private String sjjianchuMark2;

    private String sjjianchuMark3;

    private Date sjjianchuDate;

    private Date sjjianchuDate1;

    private Integer sjjianchuZong;

    private Integer sjjianchuZong1;

    private Integer sjjianchuZong2;

    private Double sjjianchuDouble;

    private Double sjjianchuDouble1;

    private Double sjjianchuDouble2;

    private Integer sjjianchuType;

    private Integer sjjianchuType1;

    private Integer sjjianchuType2;

    private Integer sjqitaId;

    private String sjqitaName;

    private Integer sjlaiyuanId;

    private String sjlaiyuanName;

    private String sjjianchuImg;

    private String sjjianchuImgName;

    private Integer shujuId;

    private String shujuName;

    private Integer sjleixingId;

    private String sjleixingName;

    private Integer sjxingtaiId;

    private String sjxingtaiName;

    private Integer userId;

    private String userName;

    private Integer bumenId;

    private String bumenName;

    private Integer buyuanId;

    private String buyuanName;

    private Integer yonghuId;

    private String yonghuName;

    private Integer byumenId;

    private String byumenName;

    private Integer byuyuanId;

    private String byuyuanName;

    private Integer buzhiId;

    private String buzhiName;

    private Integer roleId;

    private String roleName;

    private Integer byuzhiId;

    private String byuzhiName;

    private Integer yhroleId;

    private String yhroleName;

    public Integer getSjjianchuId() {
        return sjjianchuId;
    }

    public void setSjjianchuId(Integer sjjianchuId) {
        this.sjjianchuId = sjjianchuId;
    }

    public String getSjjianchuName() {
        return sjjianchuName;
    }

    public void setSjjianchuName(String sjjianchuName) {
        this.sjjianchuName = sjjianchuName == null ? null : sjjianchuName.trim();
    }

    public String getSjjianchuMark() {
        return sjjianchuMark;
    }

    public void setSjjianchuMark(String sjjianchuMark) {
        this.sjjianchuMark = sjjianchuMark == null ? null : sjjianchuMark.trim();
    }

    public String getSjjianchuMark1() {
        return sjjianchuMark1;
    }

    public void setSjjianchuMark1(String sjjianchuMark1) {
        this.sjjianchuMark1 = sjjianchuMark1 == null ? null : sjjianchuMark1.trim();
    }

    public String getSjjianchuMark2() {
        return sjjianchuMark2;
    }

    public void setSjjianchuMark2(String sjjianchuMark2) {
        this.sjjianchuMark2 = sjjianchuMark2 == null ? null : sjjianchuMark2.trim();
    }

    public String getSjjianchuMark3() {
        return sjjianchuMark3;
    }

    public void setSjjianchuMark3(String sjjianchuMark3) {
        this.sjjianchuMark3 = sjjianchuMark3 == null ? null : sjjianchuMark3.trim();
    }

    public Date getSjjianchuDate() {
        return sjjianchuDate;
    }

    public void setSjjianchuDate(Date sjjianchuDate) {
        this.sjjianchuDate = sjjianchuDate;
    }

    public Date getSjjianchuDate1() {
        return sjjianchuDate1;
    }

    public void setSjjianchuDate1(Date sjjianchuDate1) {
        this.sjjianchuDate1 = sjjianchuDate1;
    }

    public Integer getSjjianchuZong() {
        return sjjianchuZong;
    }

    public void setSjjianchuZong(Integer sjjianchuZong) {
        this.sjjianchuZong = sjjianchuZong;
    }

    public Integer getSjjianchuZong1() {
        return sjjianchuZong1;
    }

    public void setSjjianchuZong1(Integer sjjianchuZong1) {
        this.sjjianchuZong1 = sjjianchuZong1;
    }

    public Integer getSjjianchuZong2() {
        return sjjianchuZong2;
    }

    public void setSjjianchuZong2(Integer sjjianchuZong2) {
        this.sjjianchuZong2 = sjjianchuZong2;
    }

    public Double getSjjianchuDouble() {
        return sjjianchuDouble;
    }

    public void setSjjianchuDouble(Double sjjianchuDouble) {
        this.sjjianchuDouble = sjjianchuDouble;
    }

    public Double getSjjianchuDouble1() {
        return sjjianchuDouble1;
    }

    public void setSjjianchuDouble1(Double sjjianchuDouble1) {
        this.sjjianchuDouble1 = sjjianchuDouble1;
    }

    public Double getSjjianchuDouble2() {
        return sjjianchuDouble2;
    }

    public void setSjjianchuDouble2(Double sjjianchuDouble2) {
        this.sjjianchuDouble2 = sjjianchuDouble2;
    }

    public Integer getSjjianchuType() {
        return sjjianchuType;
    }

    public void setSjjianchuType(Integer sjjianchuType) {
        this.sjjianchuType = sjjianchuType;
    }

    public Integer getSjjianchuType1() {
        return sjjianchuType1;
    }

    public void setSjjianchuType1(Integer sjjianchuType1) {
        this.sjjianchuType1 = sjjianchuType1;
    }

    public Integer getSjjianchuType2() {
        return sjjianchuType2;
    }

    public void setSjjianchuType2(Integer sjjianchuType2) {
        this.sjjianchuType2 = sjjianchuType2;
    }

    public Integer getSjqitaId() {
        return sjqitaId;
    }

    public void setSjqitaId(Integer sjqitaId) {
        this.sjqitaId = sjqitaId;
    }

    public String getSjqitaName() {
        return sjqitaName;
    }

    public void setSjqitaName(String sjqitaName) {
        this.sjqitaName = sjqitaName == null ? null : sjqitaName.trim();
    }

    public Integer getSjlaiyuanId() {
        return sjlaiyuanId;
    }

    public void setSjlaiyuanId(Integer sjlaiyuanId) {
        this.sjlaiyuanId = sjlaiyuanId;
    }

    public String getSjlaiyuanName() {
        return sjlaiyuanName;
    }

    public void setSjlaiyuanName(String sjlaiyuanName) {
        this.sjlaiyuanName = sjlaiyuanName == null ? null : sjlaiyuanName.trim();
    }

    public String getSjjianchuImg() {
        return sjjianchuImg;
    }

    public void setSjjianchuImg(String sjjianchuImg) {
        this.sjjianchuImg = sjjianchuImg == null ? null : sjjianchuImg.trim();
    }

    public String getSjjianchuImgName() {
        return sjjianchuImgName;
    }

    public void setSjjianchuImgName(String sjjianchuImgName) {
        this.sjjianchuImgName = sjjianchuImgName == null ? null : sjjianchuImgName.trim();
    }

    public Integer getShujuId() {
        return shujuId;
    }

    public void setShujuId(Integer shujuId) {
        this.shujuId = shujuId;
    }

    public String getShujuName() {
        return shujuName;
    }

    public void setShujuName(String shujuName) {
        this.shujuName = shujuName == null ? null : shujuName.trim();
    }

    public Integer getSjleixingId() {
        return sjleixingId;
    }

    public void setSjleixingId(Integer sjleixingId) {
        this.sjleixingId = sjleixingId;
    }

    public String getSjleixingName() {
        return sjleixingName;
    }

    public void setSjleixingName(String sjleixingName) {
        this.sjleixingName = sjleixingName == null ? null : sjleixingName.trim();
    }

    public Integer getSjxingtaiId() {
        return sjxingtaiId;
    }

    public void setSjxingtaiId(Integer sjxingtaiId) {
        this.sjxingtaiId = sjxingtaiId;
    }

    public String getSjxingtaiName() {
        return sjxingtaiName;
    }

    public void setSjxingtaiName(String sjxingtaiName) {
        this.sjxingtaiName = sjxingtaiName == null ? null : sjxingtaiName.trim();
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    public Integer getBumenId() {
        return bumenId;
    }

    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    public String getBumenName() {
        return bumenName;
    }

    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    public Integer getBuyuanId() {
        return buyuanId;
    }

    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    public String getBuyuanName() {
        return buyuanName;
    }

    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    public Integer getYonghuId() {
        return yonghuId;
    }

    public void setYonghuId(Integer yonghuId) {
        this.yonghuId = yonghuId;
    }

    public String getYonghuName() {
        return yonghuName;
    }

    public void setYonghuName(String yonghuName) {
        this.yonghuName = yonghuName == null ? null : yonghuName.trim();
    }

    public Integer getByumenId() {
        return byumenId;
    }

    public void setByumenId(Integer byumenId) {
        this.byumenId = byumenId;
    }

    public String getByumenName() {
        return byumenName;
    }

    public void setByumenName(String byumenName) {
        this.byumenName = byumenName == null ? null : byumenName.trim();
    }

    public Integer getByuyuanId() {
        return byuyuanId;
    }

    public void setByuyuanId(Integer byuyuanId) {
        this.byuyuanId = byuyuanId;
    }

    public String getByuyuanName() {
        return byuyuanName;
    }

    public void setByuyuanName(String byuyuanName) {
        this.byuyuanName = byuyuanName == null ? null : byuyuanName.trim();
    }

    public Integer getBuzhiId() {
        return buzhiId;
    }

    public void setBuzhiId(Integer buzhiId) {
        this.buzhiId = buzhiId;
    }

    public String getBuzhiName() {
        return buzhiName;
    }

    public void setBuzhiName(String buzhiName) {
        this.buzhiName = buzhiName == null ? null : buzhiName.trim();
    }

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    public Integer getByuzhiId() {
        return byuzhiId;
    }

    public void setByuzhiId(Integer byuzhiId) {
        this.byuzhiId = byuzhiId;
    }

    public String getByuzhiName() {
        return byuzhiName;
    }

    public void setByuzhiName(String byuzhiName) {
        this.byuzhiName = byuzhiName == null ? null : byuzhiName.trim();
    }

    public Integer getYhroleId() {
        return yhroleId;
    }

    public void setYhroleId(Integer yhroleId) {
        this.yhroleId = yhroleId;
    }

    public String getYhroleName() {
        return yhroleName;
    }

    public void setYhroleName(String yhroleName) {
        this.yhroleName = yhroleName == null ? null : yhroleName.trim();
    }
}