package com.model;

import java.util.Date;

public class Sjlaiyuan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlaiyuan.sjlaiyuanId
     *
     * @mbggenerated
     */
    private Integer sjlaiyuanId;

    private String sjlaiyuanName;

    private String sjlaiyuanMark;

    private String sjlaiyuanMark1;

    private String sjlaiyuanMark2;

    private String sjlaiyuanPhone;

    private String sjlaiyuanDizhi;

    private Date sjlaiyuanDate;

    private Date sjlaiyuanDate1;

    private Integer sjlaiyuanType;

    private Integer sjlaiyuanType1;

    private Double sjlaiyuanDouble;

    private Double sjlaiyuanDouble1;

    public Integer getSjlaiyuanId() {
        return sjlaiyuanId;
    }

    public void setSjlaiyuanId(Integer sjlaiyuanId) {
        this.sjlaiyuanId = sjlaiyuanId;
    }

    public String getSjlaiyuanName() {
        return sjlaiyuanName;
    }

    public void setSjlaiyuanName(String sjlaiyuanName) {
        this.sjlaiyuanName = sjlaiyuanName == null ? null : sjlaiyuanName.trim();
    }

    public String getSjlaiyuanMark() {
        return sjlaiyuanMark;
    }

    public void setSjlaiyuanMark(String sjlaiyuanMark) {
        this.sjlaiyuanMark = sjlaiyuanMark == null ? null : sjlaiyuanMark.trim();
    }

    public String getSjlaiyuanMark1() {
        return sjlaiyuanMark1;
    }

    public void setSjlaiyuanMark1(String sjlaiyuanMark1) {
        this.sjlaiyuanMark1 = sjlaiyuanMark1 == null ? null : sjlaiyuanMark1.trim();
    }

    public String getSjlaiyuanMark2() {
        return sjlaiyuanMark2;
    }

    public void setSjlaiyuanMark2(String sjlaiyuanMark2) {
        this.sjlaiyuanMark2 = sjlaiyuanMark2 == null ? null : sjlaiyuanMark2.trim();
    }

    public String getSjlaiyuanPhone() {
        return sjlaiyuanPhone;
    }

    public void setSjlaiyuanPhone(String sjlaiyuanPhone) {
        this.sjlaiyuanPhone = sjlaiyuanPhone == null ? null : sjlaiyuanPhone.trim();
    }

    public String getSjlaiyuanDizhi() {
        return sjlaiyuanDizhi;
    }

    public void setSjlaiyuanDizhi(String sjlaiyuanDizhi) {
        this.sjlaiyuanDizhi = sjlaiyuanDizhi == null ? null : sjlaiyuanDizhi.trim();
    }

    public Date getSjlaiyuanDate() {
        return sjlaiyuanDate;
    }

    public void setSjlaiyuanDate(Date sjlaiyuanDate) {
        this.sjlaiyuanDate = sjlaiyuanDate;
    }

    public Date getSjlaiyuanDate1() {
        return sjlaiyuanDate1;
    }

    public void setSjlaiyuanDate1(Date sjlaiyuanDate1) {
        this.sjlaiyuanDate1 = sjlaiyuanDate1;
    }

    public Integer getSjlaiyuanType() {
        return sjlaiyuanType;
    }

    public void setSjlaiyuanType(Integer sjlaiyuanType) {
        this.sjlaiyuanType = sjlaiyuanType;
    }

    public Integer getSjlaiyuanType1() {
        return sjlaiyuanType1;
    }

    public void setSjlaiyuanType1(Integer sjlaiyuanType1) {
        this.sjlaiyuanType1 = sjlaiyuanType1;
    }

    public Double getSjlaiyuanDouble() {
        return sjlaiyuanDouble;
    }

    public void setSjlaiyuanDouble(Double sjlaiyuanDouble) {
        this.sjlaiyuanDouble = sjlaiyuanDouble;
    }

    public Double getSjlaiyuanDouble1() {
        return sjlaiyuanDouble1;
    }

    public void setSjlaiyuanDouble1(Double sjlaiyuanDouble1) {
        this.sjlaiyuanDouble1 = sjlaiyuanDouble1;
    }
}