package com.model;

import java.util.Date;

public class Sjleixing {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingId
     *
     * @mbggenerated
     */
    private Integer sjleixingId;

    private String sjleixingName;

    private String sjleixingMark;

    private String sjleixingMark1;

    private String sjleixingMark2;

    private String sjleixingPhone;

    private String sjleixingDizhi;

    private Date sjleixingDate;

    private Date sjleixingDate1;

    private Integer sjleixingType;

    private Integer sjleixingType1;

    private Double sjleixingDouble;

    private Double sjleixingDouble1;

    public Integer getSjleixingId() {
        return sjleixingId;
    }

    public void setSjleixingId(Integer sjleixingId) {
        this.sjleixingId = sjleixingId;
    }

    public String getSjleixingName() {
        return sjleixingName;
    }

    public void setSjleixingName(String sjleixingName) {
        this.sjleixingName = sjleixingName == null ? null : sjleixingName.trim();
    }

    public String getSjleixingMark() {
        return sjleixingMark;
    }

    public void setSjleixingMark(String sjleixingMark) {
        this.sjleixingMark = sjleixingMark == null ? null : sjleixingMark.trim();
    }

    public String getSjleixingMark1() {
        return sjleixingMark1;
    }

    public void setSjleixingMark1(String sjleixingMark1) {
        this.sjleixingMark1 = sjleixingMark1 == null ? null : sjleixingMark1.trim();
    }

    public String getSjleixingMark2() {
        return sjleixingMark2;
    }

    public void setSjleixingMark2(String sjleixingMark2) {
        this.sjleixingMark2 = sjleixingMark2 == null ? null : sjleixingMark2.trim();
    }

    public String getSjleixingPhone() {
        return sjleixingPhone;
    }

    public void setSjleixingPhone(String sjleixingPhone) {
        this.sjleixingPhone = sjleixingPhone == null ? null : sjleixingPhone.trim();
    }

    public String getSjleixingDizhi() {
        return sjleixingDizhi;
    }

    public void setSjleixingDizhi(String sjleixingDizhi) {
        this.sjleixingDizhi = sjleixingDizhi == null ? null : sjleixingDizhi.trim();
    }

    public Date getSjleixingDate() {
        return sjleixingDate;
    }

    public void setSjleixingDate(Date sjleixingDate) {
        this.sjleixingDate = sjleixingDate;
    }

    public Date getSjleixingDate1() {
        return sjleixingDate1;
    }

    public void setSjleixingDate1(Date sjleixingDate1) {
        this.sjleixingDate1 = sjleixingDate1;
    }

    public Integer getSjleixingType() {
        return sjleixingType;
    }

    public void setSjleixingType(Integer sjleixingType) {
        this.sjleixingType = sjleixingType;
    }

    public Integer getSjleixingType1() {
        return sjleixingType1;
    }

    public void setSjleixingType1(Integer sjleixingType1) {
        this.sjleixingType1 = sjleixingType1;
    }

    public Double getSjleixingDouble() {
        return sjleixingDouble;
    }

    public void setSjleixingDouble(Double sjleixingDouble) {
        this.sjleixingDouble = sjleixingDouble;
    }

    public Double getSjleixingDouble1() {
        return sjleixingDouble1;
    }

    public void setSjleixingDouble1(Double sjleixingDouble1) {
        this.sjleixingDouble1 = sjleixingDouble1;
    }
}