package com.model;

import java.util.Date;

public class Sjlianjie {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlianjie.sjlianjieId
     *
     * @mbggenerated
     */
    private Integer sjlianjieId;

    private String sjlianjieName;

    private String sjlianjieMark;

    private String sjlianjieMark1;

    private String sjlianjieMark2;

    private String sjlianjiePhone;

    private String sjlianjieDizhi;

    private Date sjlianjieDate;

    private Date sjlianjieDate1;

    private Integer sjlianjieType;

    private Integer sjlianjieType1;

    private Double sjlianjieDouble;

    private Double sjlianjieDouble1;

    public Integer getSjlianjieId() {
        return sjlianjieId;
    }

    public void setSjlianjieId(Integer sjlianjieId) {
        this.sjlianjieId = sjlianjieId;
    }

    public String getSjlianjieName() {
        return sjlianjieName;
    }

    public void setSjlianjieName(String sjlianjieName) {
        this.sjlianjieName = sjlianjieName == null ? null : sjlianjieName.trim();
    }

    public String getSjlianjieMark() {
        return sjlianjieMark;
    }

    public void setSjlianjieMark(String sjlianjieMark) {
        this.sjlianjieMark = sjlianjieMark == null ? null : sjlianjieMark.trim();
    }

    public String getSjlianjieMark1() {
        return sjlianjieMark1;
    }

    public void setSjlianjieMark1(String sjlianjieMark1) {
        this.sjlianjieMark1 = sjlianjieMark1 == null ? null : sjlianjieMark1.trim();
    }

    public String getSjlianjieMark2() {
        return sjlianjieMark2;
    }

    public void setSjlianjieMark2(String sjlianjieMark2) {
        this.sjlianjieMark2 = sjlianjieMark2 == null ? null : sjlianjieMark2.trim();
    }

    public String getSjlianjiePhone() {
        return sjlianjiePhone;
    }

    public void setSjlianjiePhone(String sjlianjiePhone) {
        this.sjlianjiePhone = sjlianjiePhone == null ? null : sjlianjiePhone.trim();
    }

    public String getSjlianjieDizhi() {
        return sjlianjieDizhi;
    }

    public void setSjlianjieDizhi(String sjlianjieDizhi) {
        this.sjlianjieDizhi = sjlianjieDizhi == null ? null : sjlianjieDizhi.trim();
    }

    public Date getSjlianjieDate() {
        return sjlianjieDate;
    }

    public void setSjlianjieDate(Date sjlianjieDate) {
        this.sjlianjieDate = sjlianjieDate;
    }

    public Date getSjlianjieDate1() {
        return sjlianjieDate1;
    }

    public void setSjlianjieDate1(Date sjlianjieDate1) {
        this.sjlianjieDate1 = sjlianjieDate1;
    }

    public Integer getSjlianjieType() {
        return sjlianjieType;
    }

    public void setSjlianjieType(Integer sjlianjieType) {
        this.sjlianjieType = sjlianjieType;
    }

    public Integer getSjlianjieType1() {
        return sjlianjieType1;
    }

    public void setSjlianjieType1(Integer sjlianjieType1) {
        this.sjlianjieType1 = sjlianjieType1;
    }

    public Double getSjlianjieDouble() {
        return sjlianjieDouble;
    }

    public void setSjlianjieDouble(Double sjlianjieDouble) {
        this.sjlianjieDouble = sjlianjieDouble;
    }

    public Double getSjlianjieDouble1() {
        return sjlianjieDouble1;
    }

    public void setSjlianjieDouble1(Double sjlianjieDouble1) {
        this.sjlianjieDouble1 = sjlianjieDouble1;
    }
}