package com.model;

import java.util.Date;

public class Sjpinglun {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjpinglun.sjpinglunId
     *
     * @mbggenerated
     */
    private Integer sjpinglunId;

    private String sjpinglunName;

    private String sjpinglunMark;

    private Date sjpinglunDate;

    private Date sjpinglunDate1;

    private Integer sjpinglunType;

    private Integer sjpinglunType1;

    private String sjpinglunImg;

    private String sjpinglunImgName;

    private Integer shujuId;

    private String shujuName;

    private Integer sjleixingId;

    private String sjleixingName;

    private Integer userId;

    private String userName;

    private Integer bumenId;

    private String bumenName;

    private Integer buyuanId;

    private String buyuanName;

    private Integer yonghuId;

    private String yonghuName;

    private Integer byumenId;

    private String byumenName;

    private Integer byuyuanId;

    private String byuyuanName;

    private Integer buzhiId;

    private String buzhiName;

    private Integer roleId;

    private String roleName;

    private Integer byuzhiId;

    private String byuzhiName;

    private Integer yhroleId;

    private String yhroleName;

    public Integer getSjpinglunId() {
        return sjpinglunId;
    }

    public void setSjpinglunId(Integer sjpinglunId) {
        this.sjpinglunId = sjpinglunId;
    }

    public String getSjpinglunName() {
        return sjpinglunName;
    }

    public void setSjpinglunName(String sjpinglunName) {
        this.sjpinglunName = sjpinglunName == null ? null : sjpinglunName.trim();
    }

    public String getSjpinglunMark() {
        return sjpinglunMark;
    }

    public void setSjpinglunMark(String sjpinglunMark) {
        this.sjpinglunMark = sjpinglunMark == null ? null : sjpinglunMark.trim();
    }

    public Date getSjpinglunDate() {
        return sjpinglunDate;
    }

    public void setSjpinglunDate(Date sjpinglunDate) {
        this.sjpinglunDate = sjpinglunDate;
    }

    public Date getSjpinglunDate1() {
        return sjpinglunDate1;
    }

    public void setSjpinglunDate1(Date sjpinglunDate1) {
        this.sjpinglunDate1 = sjpinglunDate1;
    }

    public Integer getSjpinglunType() {
        return sjpinglunType;
    }

    public void setSjpinglunType(Integer sjpinglunType) {
        this.sjpinglunType = sjpinglunType;
    }

    public Integer getSjpinglunType1() {
        return sjpinglunType1;
    }

    public void setSjpinglunType1(Integer sjpinglunType1) {
        this.sjpinglunType1 = sjpinglunType1;
    }

    public String getSjpinglunImg() {
        return sjpinglunImg;
    }

    public void setSjpinglunImg(String sjpinglunImg) {
        this.sjpinglunImg = sjpinglunImg == null ? null : sjpinglunImg.trim();
    }

    public String getSjpinglunImgName() {
        return sjpinglunImgName;
    }

    public void setSjpinglunImgName(String sjpinglunImgName) {
        this.sjpinglunImgName = sjpinglunImgName == null ? null : sjpinglunImgName.trim();
    }

    public Integer getShujuId() {
        return shujuId;
    }

    public void setShujuId(Integer shujuId) {
        this.shujuId = shujuId;
    }

    public String getShujuName() {
        return shujuName;
    }

    public void setShujuName(String shujuName) {
        this.shujuName = shujuName == null ? null : shujuName.trim();
    }

    public Integer getSjleixingId() {
        return sjleixingId;
    }

    public void setSjleixingId(Integer sjleixingId) {
        this.sjleixingId = sjleixingId;
    }

    public String getSjleixingName() {
        return sjleixingName;
    }

    public void setSjleixingName(String sjleixingName) {
        this.sjleixingName = sjleixingName == null ? null : sjleixingName.trim();
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    public Integer getBumenId() {
        return bumenId;
    }

    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    public String getBumenName() {
        return bumenName;
    }

    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    public Integer getBuyuanId() {
        return buyuanId;
    }

    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    public String getBuyuanName() {
        return buyuanName;
    }

    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    public Integer getYonghuId() {
        return yonghuId;
    }

    public void setYonghuId(Integer yonghuId) {
        this.yonghuId = yonghuId;
    }

    public String getYonghuName() {
        return yonghuName;
    }

    public void setYonghuName(String yonghuName) {
        this.yonghuName = yonghuName == null ? null : yonghuName.trim();
    }

    public Integer getByumenId() {
        return byumenId;
    }

    public void setByumenId(Integer byumenId) {
        this.byumenId = byumenId;
    }

    public String getByumenName() {
        return byumenName;
    }

    public void setByumenName(String byumenName) {
        this.byumenName = byumenName == null ? null : byumenName.trim();
    }

    public Integer getByuyuanId() {
        return byuyuanId;
    }

    public void setByuyuanId(Integer byuyuanId) {
        this.byuyuanId = byuyuanId;
    }

    public String getByuyuanName() {
        return byuyuanName;
    }

    public void setByuyuanName(String byuyuanName) {
        this.byuyuanName = byuyuanName == null ? null : byuyuanName.trim();
    }

    public Integer getBuzhiId() {
        return buzhiId;
    }

    public void setBuzhiId(Integer buzhiId) {
        this.buzhiId = buzhiId;
    }

    public String getBuzhiName() {
        return buzhiName;
    }

    public void setBuzhiName(String buzhiName) {
        this.buzhiName = buzhiName == null ? null : buzhiName.trim();
    }

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    public Integer getByuzhiId() {
        return byuzhiId;
    }

    public void setByuzhiId(Integer byuzhiId) {
        this.byuzhiId = byuzhiId;
    }

    public String getByuzhiName() {
        return byuzhiName;
    }

    public void setByuzhiName(String byuzhiName) {
        this.byuzhiName = byuzhiName == null ? null : byuzhiName.trim();
    }

    public Integer getYhroleId() {
        return yhroleId;
    }

    public void setYhroleId(Integer yhroleId) {
        this.yhroleId = yhroleId;
    }

    public String getYhroleName() {
        return yhroleName;
    }

    public void setYhroleName(String yhroleName) {
        this.yhroleName = yhroleName == null ? null : yhroleName.trim();
    }
}