package com.model;

import java.util.Date;

public class Sjqita {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjqita.sjqitaId
     *
     * @mbggenerated
     */
    private Integer sjqitaId;

    private String sjqitaName;

    private String sjqitaMark;

    private String sjqitaMark1;

    private String sjqitaMark2;

    private String sjqitaPhone;

    private String sjqitaDizhi;

    private Date sjqitaDate;

    private Date sjqitaDate1;

    private Integer sjqitaType;

    private Integer sjqitaType1;

    private Double sjqitaDouble;

    private Double sjqitaDouble1;

    public Integer getSjqitaId() {
        return sjqitaId;
    }

    public void setSjqitaId(Integer sjqitaId) {
        this.sjqitaId = sjqitaId;
    }

    public String getSjqitaName() {
        return sjqitaName;
    }

    public void setSjqitaName(String sjqitaName) {
        this.sjqitaName = sjqitaName == null ? null : sjqitaName.trim();
    }

    public String getSjqitaMark() {
        return sjqitaMark;
    }

    public void setSjqitaMark(String sjqitaMark) {
        this.sjqitaMark = sjqitaMark == null ? null : sjqitaMark.trim();
    }

    public String getSjqitaMark1() {
        return sjqitaMark1;
    }

    public void setSjqitaMark1(String sjqitaMark1) {
        this.sjqitaMark1 = sjqitaMark1 == null ? null : sjqitaMark1.trim();
    }

    public String getSjqitaMark2() {
        return sjqitaMark2;
    }

    public void setSjqitaMark2(String sjqitaMark2) {
        this.sjqitaMark2 = sjqitaMark2 == null ? null : sjqitaMark2.trim();
    }

    public String getSjqitaPhone() {
        return sjqitaPhone;
    }

    public void setSjqitaPhone(String sjqitaPhone) {
        this.sjqitaPhone = sjqitaPhone == null ? null : sjqitaPhone.trim();
    }

    public String getSjqitaDizhi() {
        return sjqitaDizhi;
    }

    public void setSjqitaDizhi(String sjqitaDizhi) {
        this.sjqitaDizhi = sjqitaDizhi == null ? null : sjqitaDizhi.trim();
    }

    public Date getSjqitaDate() {
        return sjqitaDate;
    }

    public void setSjqitaDate(Date sjqitaDate) {
        this.sjqitaDate = sjqitaDate;
    }

    public Date getSjqitaDate1() {
        return sjqitaDate1;
    }

    public void setSjqitaDate1(Date sjqitaDate1) {
        this.sjqitaDate1 = sjqitaDate1;
    }

    public Integer getSjqitaType() {
        return sjqitaType;
    }

    public void setSjqitaType(Integer sjqitaType) {
        this.sjqitaType = sjqitaType;
    }

    public Integer getSjqitaType1() {
        return sjqitaType1;
    }

    public void setSjqitaType1(Integer sjqitaType1) {
        this.sjqitaType1 = sjqitaType1;
    }

    public Double getSjqitaDouble() {
        return sjqitaDouble;
    }

    public void setSjqitaDouble(Double sjqitaDouble) {
        this.sjqitaDouble = sjqitaDouble;
    }

    public Double getSjqitaDouble1() {
        return sjqitaDouble1;
    }

    public void setSjqitaDouble1(Double sjqitaDouble1) {
        this.sjqitaDouble1 = sjqitaDouble1;
    }
}