package com.model;

import java.util.Date;

public class Sjshaochu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjshaochuId
     *
     * @mbggenerated
     */
    private Integer sjshaochuId;

    private String sjshaochuName;

    private String sjshaochuMark;

    private String sjshaochuMark1;

    private String sjshaochuMark2;

    private String sjshaochuMark3;

    private Date sjshaochuDate;

    private Date sjshaochuDate1;

    private Integer sjshaochuZong;

    private Integer sjshaochuZong1;

    private Integer sjshaochuZong2;

    private Double sjshaochuDouble;

    private Double sjshaochuDouble1;

    private Double sjshaochuDouble2;

    private Integer sjshaochuType;

    private Integer sjshaochuType1;

    private Integer sjshaochuType2;

    private Integer sjqitaId;

    private String sjqitaName;

    private Integer sjlaiyuanId;

    private String sjlaiyuanName;

    private String sjshaochuImg;

    private String sjshaochuImgName;

    private Integer shujuId;

    private String shujuName;

    private Integer sjleixingId;

    private String sjleixingName;

    private Integer sjxingtaiId;

    private String sjxingtaiName;

    private Integer userId;

    private String userName;

    private Integer bumenId;

    private String bumenName;

    private Integer buyuanId;

    private String buyuanName;

    private Integer yonghuId;

    private String yonghuName;

    private Integer byumenId;

    private String byumenName;

    private Integer byuyuanId;

    private String byuyuanName;

    private Integer buzhiId;

    private String buzhiName;

    private Integer roleId;

    private String roleName;

    private Integer byuzhiId;

    private String byuzhiName;

    private Integer yhroleId;

    private String yhroleName;

    public Integer getSjshaochuId() {
        return sjshaochuId;
    }

    public void setSjshaochuId(Integer sjshaochuId) {
        this.sjshaochuId = sjshaochuId;
    }

    public String getSjshaochuName() {
        return sjshaochuName;
    }

    public void setSjshaochuName(String sjshaochuName) {
        this.sjshaochuName = sjshaochuName == null ? null : sjshaochuName.trim();
    }

    public String getSjshaochuMark() {
        return sjshaochuMark;
    }

    public void setSjshaochuMark(String sjshaochuMark) {
        this.sjshaochuMark = sjshaochuMark == null ? null : sjshaochuMark.trim();
    }

    public String getSjshaochuMark1() {
        return sjshaochuMark1;
    }

    public void setSjshaochuMark1(String sjshaochuMark1) {
        this.sjshaochuMark1 = sjshaochuMark1 == null ? null : sjshaochuMark1.trim();
    }

    public String getSjshaochuMark2() {
        return sjshaochuMark2;
    }

    public void setSjshaochuMark2(String sjshaochuMark2) {
        this.sjshaochuMark2 = sjshaochuMark2 == null ? null : sjshaochuMark2.trim();
    }

    public String getSjshaochuMark3() {
        return sjshaochuMark3;
    }

    public void setSjshaochuMark3(String sjshaochuMark3) {
        this.sjshaochuMark3 = sjshaochuMark3 == null ? null : sjshaochuMark3.trim();
    }

    public Date getSjshaochuDate() {
        return sjshaochuDate;
    }

    public void setSjshaochuDate(Date sjshaochuDate) {
        this.sjshaochuDate = sjshaochuDate;
    }

    public Date getSjshaochuDate1() {
        return sjshaochuDate1;
    }

    public void setSjshaochuDate1(Date sjshaochuDate1) {
        this.sjshaochuDate1 = sjshaochuDate1;
    }

    public Integer getSjshaochuZong() {
        return sjshaochuZong;
    }

    public void setSjshaochuZong(Integer sjshaochuZong) {
        this.sjshaochuZong = sjshaochuZong;
    }

    public Integer getSjshaochuZong1() {
        return sjshaochuZong1;
    }

    public void setSjshaochuZong1(Integer sjshaochuZong1) {
        this.sjshaochuZong1 = sjshaochuZong1;
    }

    public Integer getSjshaochuZong2() {
        return sjshaochuZong2;
    }

    public void setSjshaochuZong2(Integer sjshaochuZong2) {
        this.sjshaochuZong2 = sjshaochuZong2;
    }

    public Double getSjshaochuDouble() {
        return sjshaochuDouble;
    }

    public void setSjshaochuDouble(Double sjshaochuDouble) {
        this.sjshaochuDouble = sjshaochuDouble;
    }

    public Double getSjshaochuDouble1() {
        return sjshaochuDouble1;
    }

    public void setSjshaochuDouble1(Double sjshaochuDouble1) {
        this.sjshaochuDouble1 = sjshaochuDouble1;
    }

    public Double getSjshaochuDouble2() {
        return sjshaochuDouble2;
    }

    public void setSjshaochuDouble2(Double sjshaochuDouble2) {
        this.sjshaochuDouble2 = sjshaochuDouble2;
    }

    public Integer getSjshaochuType() {
        return sjshaochuType;
    }

    public void setSjshaochuType(Integer sjshaochuType) {
        this.sjshaochuType = sjshaochuType;
    }

    public Integer getSjshaochuType1() {
        return sjshaochuType1;
    }

    public void setSjshaochuType1(Integer sjshaochuType1) {
        this.sjshaochuType1 = sjshaochuType1;
    }

    public Integer getSjshaochuType2() {
        return sjshaochuType2;
    }

    public void setSjshaochuType2(Integer sjshaochuType2) {
        this.sjshaochuType2 = sjshaochuType2;
    }

    public Integer getSjqitaId() {
        return sjqitaId;
    }

    public void setSjqitaId(Integer sjqitaId) {
        this.sjqitaId = sjqitaId;
    }

    public String getSjqitaName() {
        return sjqitaName;
    }

    public void setSjqitaName(String sjqitaName) {
        this.sjqitaName = sjqitaName == null ? null : sjqitaName.trim();
    }

    public Integer getSjlaiyuanId() {
        return sjlaiyuanId;
    }

    public void setSjlaiyuanId(Integer sjlaiyuanId) {
        this.sjlaiyuanId = sjlaiyuanId;
    }

    public String getSjlaiyuanName() {
        return sjlaiyuanName;
    }

    public void setSjlaiyuanName(String sjlaiyuanName) {
        this.sjlaiyuanName = sjlaiyuanName == null ? null : sjlaiyuanName.trim();
    }

    public String getSjshaochuImg() {
        return sjshaochuImg;
    }

    public void setSjshaochuImg(String sjshaochuImg) {
        this.sjshaochuImg = sjshaochuImg == null ? null : sjshaochuImg.trim();
    }

    public String getSjshaochuImgName() {
        return sjshaochuImgName;
    }

    public void setSjshaochuImgName(String sjshaochuImgName) {
        this.sjshaochuImgName = sjshaochuImgName == null ? null : sjshaochuImgName.trim();
    }

    public Integer getShujuId() {
        return shujuId;
    }

    public void setShujuId(Integer shujuId) {
        this.shujuId = shujuId;
    }

    public String getShujuName() {
        return shujuName;
    }

    public void setShujuName(String shujuName) {
        this.shujuName = shujuName == null ? null : shujuName.trim();
    }

    public Integer getSjleixingId() {
        return sjleixingId;
    }

    public void setSjleixingId(Integer sjleixingId) {
        this.sjleixingId = sjleixingId;
    }

    public String getSjleixingName() {
        return sjleixingName;
    }

    public void setSjleixingName(String sjleixingName) {
        this.sjleixingName = sjleixingName == null ? null : sjleixingName.trim();
    }

    public Integer getSjxingtaiId() {
        return sjxingtaiId;
    }

    public void setSjxingtaiId(Integer sjxingtaiId) {
        this.sjxingtaiId = sjxingtaiId;
    }

    public String getSjxingtaiName() {
        return sjxingtaiName;
    }

    public void setSjxingtaiName(String sjxingtaiName) {
        this.sjxingtaiName = sjxingtaiName == null ? null : sjxingtaiName.trim();
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    public Integer getBumenId() {
        return bumenId;
    }

    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    public String getBumenName() {
        return bumenName;
    }

    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    public Integer getBuyuanId() {
        return buyuanId;
    }

    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    public String getBuyuanName() {
        return buyuanName;
    }

    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    public Integer getYonghuId() {
        return yonghuId;
    }

    public void setYonghuId(Integer yonghuId) {
        this.yonghuId = yonghuId;
    }

    public String getYonghuName() {
        return yonghuName;
    }

    public void setYonghuName(String yonghuName) {
        this.yonghuName = yonghuName == null ? null : yonghuName.trim();
    }

    public Integer getByumenId() {
        return byumenId;
    }

    public void setByumenId(Integer byumenId) {
        this.byumenId = byumenId;
    }

    public String getByumenName() {
        return byumenName;
    }

    public void setByumenName(String byumenName) {
        this.byumenName = byumenName == null ? null : byumenName.trim();
    }

    public Integer getByuyuanId() {
        return byuyuanId;
    }

    public void setByuyuanId(Integer byuyuanId) {
        this.byuyuanId = byuyuanId;
    }

    public String getByuyuanName() {
        return byuyuanName;
    }

    public void setByuyuanName(String byuyuanName) {
        this.byuyuanName = byuyuanName == null ? null : byuyuanName.trim();
    }

    public Integer getBuzhiId() {
        return buzhiId;
    }

    public void setBuzhiId(Integer buzhiId) {
        this.buzhiId = buzhiId;
    }

    public String getBuzhiName() {
        return buzhiName;
    }

    public void setBuzhiName(String buzhiName) {
        this.buzhiName = buzhiName == null ? null : buzhiName.trim();
    }

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    public Integer getByuzhiId() {
        return byuzhiId;
    }

    public void setByuzhiId(Integer byuzhiId) {
        this.byuzhiId = byuzhiId;
    }

    public String getByuzhiName() {
        return byuzhiName;
    }

    public void setByuzhiName(String byuzhiName) {
        this.byuzhiName = byuzhiName == null ? null : byuzhiName.trim();
    }

    public Integer getYhroleId() {
        return yhroleId;
    }

    public void setYhroleId(Integer yhroleId) {
        this.yhroleId = yhroleId;
    }

    public String getYhroleName() {
        return yhroleName;
    }

    public void setYhroleName(String yhroleName) {
        this.yhroleName = yhroleName == null ? null : yhroleName.trim();
    }
}