package com.model;

import java.util.Date;

public class Sjxiaoxi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxiaoxi.sjxiaoxiId
     *
     * @mbggenerated
     */
    private Integer sjxiaoxiId;

    private String sjxiaoxiName;

    private String sjxiaoxiMark;

    private String sjxiaoxiMark1;

    private String sjxiaoxiMark2;

    private String sjxiaoxiPhone;

    private String sjxiaoxiDizhi;

    private Date sjxiaoxiDate;

    private Date sjxiaoxiDate1;

    private Integer sjxiaoxiType;

    private Integer sjxiaoxiType1;

    private Double sjxiaoxiDouble;

    private Double sjxiaoxiDouble1;

    public Integer getSjxiaoxiId() {
        return sjxiaoxiId;
    }

    public void setSjxiaoxiId(Integer sjxiaoxiId) {
        this.sjxiaoxiId = sjxiaoxiId;
    }

    public String getSjxiaoxiName() {
        return sjxiaoxiName;
    }

    public void setSjxiaoxiName(String sjxiaoxiName) {
        this.sjxiaoxiName = sjxiaoxiName == null ? null : sjxiaoxiName.trim();
    }

    public String getSjxiaoxiMark() {
        return sjxiaoxiMark;
    }

    public void setSjxiaoxiMark(String sjxiaoxiMark) {
        this.sjxiaoxiMark = sjxiaoxiMark == null ? null : sjxiaoxiMark.trim();
    }

    public String getSjxiaoxiMark1() {
        return sjxiaoxiMark1;
    }

    public void setSjxiaoxiMark1(String sjxiaoxiMark1) {
        this.sjxiaoxiMark1 = sjxiaoxiMark1 == null ? null : sjxiaoxiMark1.trim();
    }

    public String getSjxiaoxiMark2() {
        return sjxiaoxiMark2;
    }

    public void setSjxiaoxiMark2(String sjxiaoxiMark2) {
        this.sjxiaoxiMark2 = sjxiaoxiMark2 == null ? null : sjxiaoxiMark2.trim();
    }

    public String getSjxiaoxiPhone() {
        return sjxiaoxiPhone;
    }

    public void setSjxiaoxiPhone(String sjxiaoxiPhone) {
        this.sjxiaoxiPhone = sjxiaoxiPhone == null ? null : sjxiaoxiPhone.trim();
    }

    public String getSjxiaoxiDizhi() {
        return sjxiaoxiDizhi;
    }

    public void setSjxiaoxiDizhi(String sjxiaoxiDizhi) {
        this.sjxiaoxiDizhi = sjxiaoxiDizhi == null ? null : sjxiaoxiDizhi.trim();
    }

    public Date getSjxiaoxiDate() {
        return sjxiaoxiDate;
    }

    public void setSjxiaoxiDate(Date sjxiaoxiDate) {
        this.sjxiaoxiDate = sjxiaoxiDate;
    }

    public Date getSjxiaoxiDate1() {
        return sjxiaoxiDate1;
    }

    public void setSjxiaoxiDate1(Date sjxiaoxiDate1) {
        this.sjxiaoxiDate1 = sjxiaoxiDate1;
    }

    public Integer getSjxiaoxiType() {
        return sjxiaoxiType;
    }

    public void setSjxiaoxiType(Integer sjxiaoxiType) {
        this.sjxiaoxiType = sjxiaoxiType;
    }

    public Integer getSjxiaoxiType1() {
        return sjxiaoxiType1;
    }

    public void setSjxiaoxiType1(Integer sjxiaoxiType1) {
        this.sjxiaoxiType1 = sjxiaoxiType1;
    }

    public Double getSjxiaoxiDouble() {
        return sjxiaoxiDouble;
    }

    public void setSjxiaoxiDouble(Double sjxiaoxiDouble) {
        this.sjxiaoxiDouble = sjxiaoxiDouble;
    }

    public Double getSjxiaoxiDouble1() {
        return sjxiaoxiDouble1;
    }

    public void setSjxiaoxiDouble1(Double sjxiaoxiDouble1) {
        this.sjxiaoxiDouble1 = sjxiaoxiDouble1;
    }
}