package com.model;

import java.util.Date;

public class Sjxingtai {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxingtai.sjxingtaiId
     *
     * @mbggenerated
     */
    private Integer sjxingtaiId;

    private String sjxingtaiName;

    private String sjxingtaiMark;

    private String sjxingtaiMark1;

    private String sjxingtaiMark2;

    private String sjxingtaiPhone;

    private String sjxingtaiDizhi;

    private Date sjxingtaiDate;

    private Date sjxingtaiDate1;

    private Integer sjxingtaiType;

    private Integer sjxingtaiType1;

    private Double sjxingtaiDouble;

    private Double sjxingtaiDouble1;

    public Integer getSjxingtaiId() {
        return sjxingtaiId;
    }

    public void setSjxingtaiId(Integer sjxingtaiId) {
        this.sjxingtaiId = sjxingtaiId;
    }

    public String getSjxingtaiName() {
        return sjxingtaiName;
    }

    public void setSjxingtaiName(String sjxingtaiName) {
        this.sjxingtaiName = sjxingtaiName == null ? null : sjxingtaiName.trim();
    }

    public String getSjxingtaiMark() {
        return sjxingtaiMark;
    }

    public void setSjxingtaiMark(String sjxingtaiMark) {
        this.sjxingtaiMark = sjxingtaiMark == null ? null : sjxingtaiMark.trim();
    }

    public String getSjxingtaiMark1() {
        return sjxingtaiMark1;
    }

    public void setSjxingtaiMark1(String sjxingtaiMark1) {
        this.sjxingtaiMark1 = sjxingtaiMark1 == null ? null : sjxingtaiMark1.trim();
    }

    public String getSjxingtaiMark2() {
        return sjxingtaiMark2;
    }

    public void setSjxingtaiMark2(String sjxingtaiMark2) {
        this.sjxingtaiMark2 = sjxingtaiMark2 == null ? null : sjxingtaiMark2.trim();
    }

    public String getSjxingtaiPhone() {
        return sjxingtaiPhone;
    }

    public void setSjxingtaiPhone(String sjxingtaiPhone) {
        this.sjxingtaiPhone = sjxingtaiPhone == null ? null : sjxingtaiPhone.trim();
    }

    public String getSjxingtaiDizhi() {
        return sjxingtaiDizhi;
    }

    public void setSjxingtaiDizhi(String sjxingtaiDizhi) {
        this.sjxingtaiDizhi = sjxingtaiDizhi == null ? null : sjxingtaiDizhi.trim();
    }

    public Date getSjxingtaiDate() {
        return sjxingtaiDate;
    }

    public void setSjxingtaiDate(Date sjxingtaiDate) {
        this.sjxingtaiDate = sjxingtaiDate;
    }

    public Date getSjxingtaiDate1() {
        return sjxingtaiDate1;
    }

    public void setSjxingtaiDate1(Date sjxingtaiDate1) {
        this.sjxingtaiDate1 = sjxingtaiDate1;
    }

    public Integer getSjxingtaiType() {
        return sjxingtaiType;
    }

    public void setSjxingtaiType(Integer sjxingtaiType) {
        this.sjxingtaiType = sjxingtaiType;
    }

    public Integer getSjxingtaiType1() {
        return sjxingtaiType1;
    }

    public void setSjxingtaiType1(Integer sjxingtaiType1) {
        this.sjxingtaiType1 = sjxingtaiType1;
    }

    public Double getSjxingtaiDouble() {
        return sjxingtaiDouble;
    }

    public void setSjxingtaiDouble(Double sjxingtaiDouble) {
        this.sjxingtaiDouble = sjxingtaiDouble;
    }

    public Double getSjxingtaiDouble1() {
        return sjxingtaiDouble1;
    }

    public void setSjxingtaiDouble1(Double sjxingtaiDouble1) {
        this.sjxingtaiDouble1 = sjxingtaiDouble1;
    }
}