package com.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    private String userName;

    private String userPassword;

    private String userXingming;

    private Integer userSex;

    private Integer userAge;

    private String userMinzu;

    private String userPhone;

    private String userMark;

    private String userMark1;

    private String userMark2;

    private String userMark3;

    private String userMark4;

    private Date userDate;

    private Date userDate1;

    private Date userDate2;

    private Integer userType;

    private Integer userType1;

    private Integer userType2;

    private Double userDouble;

    private Double userDouble1;

    private Double userDouble2;

    private Integer userZong;

    private Integer userZong1;

    private Integer userZong2;

    private String userImg;

    private String userImgName;

    private Integer roleId;

    private String roleName;

    private Integer bumenId;

    private String bumenName;

    private Integer buyuanId;

    private String buyuanName;

    private Integer buzhiId;

    private String buzhiName;

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    public String getUserPassword() {
        return userPassword;
    }

    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    public String getUserXingming() {
        return userXingming;
    }

    public void setUserXingming(String userXingming) {
        this.userXingming = userXingming == null ? null : userXingming.trim();
    }

    public Integer getUserSex() {
        return userSex;
    }

    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }

    public Integer getUserAge() {
        return userAge;
    }

    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

    public String getUserMinzu() {
        return userMinzu;
    }

    public void setUserMinzu(String userMinzu) {
        this.userMinzu = userMinzu == null ? null : userMinzu.trim();
    }

    public String getUserPhone() {
        return userPhone;
    }

    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    public String getUserMark() {
        return userMark;
    }

    public void setUserMark(String userMark) {
        this.userMark = userMark == null ? null : userMark.trim();
    }

    public String getUserMark1() {
        return userMark1;
    }

    public void setUserMark1(String userMark1) {
        this.userMark1 = userMark1 == null ? null : userMark1.trim();
    }

    public String getUserMark2() {
        return userMark2;
    }

    public void setUserMark2(String userMark2) {
        this.userMark2 = userMark2 == null ? null : userMark2.trim();
    }

    public String getUserMark3() {
        return userMark3;
    }

    public void setUserMark3(String userMark3) {
        this.userMark3 = userMark3 == null ? null : userMark3.trim();
    }

    public String getUserMark4() {
        return userMark4;
    }

    public void setUserMark4(String userMark4) {
        this.userMark4 = userMark4 == null ? null : userMark4.trim();
    }

    public Date getUserDate() {
        return userDate;
    }

    public void setUserDate(Date userDate) {
        this.userDate = userDate;
    }

    public Date getUserDate1() {
        return userDate1;
    }

    public void setUserDate1(Date userDate1) {
        this.userDate1 = userDate1;
    }

    public Date getUserDate2() {
        return userDate2;
    }

    public void setUserDate2(Date userDate2) {
        this.userDate2 = userDate2;
    }

    public Integer getUserType() {
        return userType;
    }

    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    public Integer getUserType1() {
        return userType1;
    }

    public void setUserType1(Integer userType1) {
        this.userType1 = userType1;
    }

    public Integer getUserType2() {
        return userType2;
    }

    public void setUserType2(Integer userType2) {
        this.userType2 = userType2;
    }

    public Double getUserDouble() {
        return userDouble;
    }

    public void setUserDouble(Double userDouble) {
        this.userDouble = userDouble;
    }

    public Double getUserDouble1() {
        return userDouble1;
    }

    public void setUserDouble1(Double userDouble1) {
        this.userDouble1 = userDouble1;
    }

    public Double getUserDouble2() {
        return userDouble2;
    }

    public void setUserDouble2(Double userDouble2) {
        this.userDouble2 = userDouble2;
    }

    public Integer getUserZong() {
        return userZong;
    }

    public void setUserZong(Integer userZong) {
        this.userZong = userZong;
    }

    public Integer getUserZong1() {
        return userZong1;
    }

    public void setUserZong1(Integer userZong1) {
        this.userZong1 = userZong1;
    }

    public Integer getUserZong2() {
        return userZong2;
    }

    public void setUserZong2(Integer userZong2) {
        this.userZong2 = userZong2;
    }

    public String getUserImg() {
        return userImg;
    }

    public void setUserImg(String userImg) {
        this.userImg = userImg == null ? null : userImg.trim();
    }

    public String getUserImgName() {
        return userImgName;
    }

    public void setUserImgName(String userImgName) {
        this.userImgName = userImgName == null ? null : userImgName.trim();
    }

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    public Integer getBumenId() {
        return bumenId;
    }

    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    public String getBumenName() {
        return bumenName;
    }

    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    public Integer getBuyuanId() {
        return buyuanId;
    }

    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    public String getBuyuanName() {
        return buyuanName;
    }

    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    public Integer getBuzhiId() {
        return buzhiId;
    }

    public void setBuzhiId(Integer buzhiId) {
        this.buzhiId = buzhiId;
    }

    public String getBuzhiName() {
        return buzhiName;
    }

    public void setBuzhiName(String buzhiName) {
        this.buzhiName = buzhiName == null ? null : buzhiName.trim();
    }
}