package com.model;

import java.util.Date;

public class Uxinxi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.uxinxiId
     *
     * @mbggenerated
     */
    private Integer uxinxiId;

    private String uxinxiName;

    private String uxinxiMark;

    private String uxinxiMark1;

    private String uxinxiMark2;

    private String uxinxiImg;

    private String uxinxiImgName;

    private Date uxinxiDate;

    private Integer uxinxiZong;

    private Integer uxinxiZong1;

    private Integer uxinxiZong2;

    private Double uxinxiDouble;

    private Double uxinxiDouble1;

    private Double uxinxiDouble2;

    private Integer uxinxiType;

    private Integer uxinxiType1;

    private Integer uxinxiType2;

    private Integer uxtypeId;

    private String uxtypeName;

    private Integer userId;

    private String userName;

    private Integer bumenId;

    private String bumenName;

    private Integer buyuanId;

    private String buyuanName;

    private Integer buzhiId;

    private String buzhiName;

    private Integer roleId;

    private String roleName;

    public Integer getUxinxiId() {
        return uxinxiId;
    }

    public void setUxinxiId(Integer uxinxiId) {
        this.uxinxiId = uxinxiId;
    }

    public String getUxinxiName() {
        return uxinxiName;
    }

    public void setUxinxiName(String uxinxiName) {
        this.uxinxiName = uxinxiName == null ? null : uxinxiName.trim();
    }

    public String getUxinxiMark() {
        return uxinxiMark;
    }

    public void setUxinxiMark(String uxinxiMark) {
        this.uxinxiMark = uxinxiMark == null ? null : uxinxiMark.trim();
    }

    public String getUxinxiMark1() {
        return uxinxiMark1;
    }

    public void setUxinxiMark1(String uxinxiMark1) {
        this.uxinxiMark1 = uxinxiMark1 == null ? null : uxinxiMark1.trim();
    }

    public String getUxinxiMark2() {
        return uxinxiMark2;
    }

    public void setUxinxiMark2(String uxinxiMark2) {
        this.uxinxiMark2 = uxinxiMark2 == null ? null : uxinxiMark2.trim();
    }

    public String getUxinxiImg() {
        return uxinxiImg;
    }

    public void setUxinxiImg(String uxinxiImg) {
        this.uxinxiImg = uxinxiImg == null ? null : uxinxiImg.trim();
    }

    public String getUxinxiImgName() {
        return uxinxiImgName;
    }

    public void setUxinxiImgName(String uxinxiImgName) {
        this.uxinxiImgName = uxinxiImgName == null ? null : uxinxiImgName.trim();
    }

    public Date getUxinxiDate() {
        return uxinxiDate;
    }

    public void setUxinxiDate(Date uxinxiDate) {
        this.uxinxiDate = uxinxiDate;
    }

    public Integer getUxinxiZong() {
        return uxinxiZong;
    }

    public void setUxinxiZong(Integer uxinxiZong) {
        this.uxinxiZong = uxinxiZong;
    }

    public Integer getUxinxiZong1() {
        return uxinxiZong1;
    }

    public void setUxinxiZong1(Integer uxinxiZong1) {
        this.uxinxiZong1 = uxinxiZong1;
    }

    public Integer getUxinxiZong2() {
        return uxinxiZong2;
    }

    public void setUxinxiZong2(Integer uxinxiZong2) {
        this.uxinxiZong2 = uxinxiZong2;
    }

    public Double getUxinxiDouble() {
        return uxinxiDouble;
    }

    public void setUxinxiDouble(Double uxinxiDouble) {
        this.uxinxiDouble = uxinxiDouble;
    }

    public Double getUxinxiDouble1() {
        return uxinxiDouble1;
    }

    public void setUxinxiDouble1(Double uxinxiDouble1) {
        this.uxinxiDouble1 = uxinxiDouble1;
    }

    public Double getUxinxiDouble2() {
        return uxinxiDouble2;
    }

    public void setUxinxiDouble2(Double uxinxiDouble2) {
        this.uxinxiDouble2 = uxinxiDouble2;
    }

    public Integer getUxinxiType() {
        return uxinxiType;
    }

    public void setUxinxiType(Integer uxinxiType) {
        this.uxinxiType = uxinxiType;
    }

    public Integer getUxinxiType1() {
        return uxinxiType1;
    }

    public void setUxinxiType1(Integer uxinxiType1) {
        this.uxinxiType1 = uxinxiType1;
    }

    public Integer getUxinxiType2() {
        return uxinxiType2;
    }

    public void setUxinxiType2(Integer uxinxiType2) {
        this.uxinxiType2 = uxinxiType2;
    }

    public Integer getUxtypeId() {
        return uxtypeId;
    }

    public void setUxtypeId(Integer uxtypeId) {
        this.uxtypeId = uxtypeId;
    }

    public String getUxtypeName() {
        return uxtypeName;
    }

    public void setUxtypeName(String uxtypeName) {
        this.uxtypeName = uxtypeName == null ? null : uxtypeName.trim();
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    public Integer getBumenId() {
        return bumenId;
    }

    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    public String getBumenName() {
        return bumenName;
    }

    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    public Integer getBuyuanId() {
        return buyuanId;
    }

    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    public String getBuyuanName() {
        return buyuanName;
    }

    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    public Integer getBuzhiId() {
        return buzhiId;
    }

    public void setBuzhiId(Integer buzhiId) {
        this.buzhiId = buzhiId;
    }

    public String getBuzhiName() {
        return buzhiName;
    }

    public void setBuzhiName(String buzhiName) {
        this.buzhiName = buzhiName == null ? null : buzhiName.trim();
    }

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }
}