package com.model;

public class Uxtype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxtype.uxtypeId
     *
     * @mbggenerated
     */
    private Integer uxtypeId;

    private String uxtypeName;

    private String uxtypeMark;

    public Integer getUxtypeId() {
        return uxtypeId;
    }

    public void setUxtypeId(Integer uxtypeId) {
        this.uxtypeId = uxtypeId;
    }

    public String getUxtypeName() {
        return uxtypeName;
    }

    public void setUxtypeName(String uxtypeName) {
        this.uxtypeName = uxtypeName == null ? null : uxtypeName.trim();
    }

    public String getUxtypeMark() {
        return uxtypeMark;
    }

    public void setUxtypeMark(String uxtypeMark) {
        this.uxtypeMark = uxtypeMark == null ? null : uxtypeMark.trim();
    }
}