package com.model;

import java.util.Date;

public class Uyijian {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.uyijianId
     *
     * @mbggenerated
     */
    private Integer uyijianId;

    private String uyijianName;

    private String uyijianMark;

    private String uyijianMark1;

    private String uyijianMark2;

    private String uyijianImg;

    private String uyijianImgName;

    private Date uyijianDate;

    private Integer uyijianZong;

    private Integer uyijianZong1;

    private Integer uyijianZong2;

    private Double uyijianDouble;

    private Double uyijianDouble1;

    private Double uyijianDouble2;

    private Integer uyijianType;

    private Integer uyijianType1;

    private Integer uyijianType2;

    private Integer uxtypeId;

    private String uxtypeName;

    private Integer userId;

    private String userName;

    private Integer bumenId;

    private String bumenName;

    private Integer buyuanId;

    private String buyuanName;

    private Integer buzhiId;

    private String buzhiName;

    private Integer roleId;

    private String roleName;

    public Integer getUyijianId() {
        return uyijianId;
    }

    public void setUyijianId(Integer uyijianId) {
        this.uyijianId = uyijianId;
    }

    public String getUyijianName() {
        return uyijianName;
    }

    public void setUyijianName(String uyijianName) {
        this.uyijianName = uyijianName == null ? null : uyijianName.trim();
    }

    public String getUyijianMark() {
        return uyijianMark;
    }

    public void setUyijianMark(String uyijianMark) {
        this.uyijianMark = uyijianMark == null ? null : uyijianMark.trim();
    }

    public String getUyijianMark1() {
        return uyijianMark1;
    }

    public void setUyijianMark1(String uyijianMark1) {
        this.uyijianMark1 = uyijianMark1 == null ? null : uyijianMark1.trim();
    }

    public String getUyijianMark2() {
        return uyijianMark2;
    }

    public void setUyijianMark2(String uyijianMark2) {
        this.uyijianMark2 = uyijianMark2 == null ? null : uyijianMark2.trim();
    }

    public String getUyijianImg() {
        return uyijianImg;
    }

    public void setUyijianImg(String uyijianImg) {
        this.uyijianImg = uyijianImg == null ? null : uyijianImg.trim();
    }

    public String getUyijianImgName() {
        return uyijianImgName;
    }

    public void setUyijianImgName(String uyijianImgName) {
        this.uyijianImgName = uyijianImgName == null ? null : uyijianImgName.trim();
    }

    public Date getUyijianDate() {
        return uyijianDate;
    }

    public void setUyijianDate(Date uyijianDate) {
        this.uyijianDate = uyijianDate;
    }

    public Integer getUyijianZong() {
        return uyijianZong;
    }

    public void setUyijianZong(Integer uyijianZong) {
        this.uyijianZong = uyijianZong;
    }

    public Integer getUyijianZong1() {
        return uyijianZong1;
    }

    public void setUyijianZong1(Integer uyijianZong1) {
        this.uyijianZong1 = uyijianZong1;
    }

    public Integer getUyijianZong2() {
        return uyijianZong2;
    }

    public void setUyijianZong2(Integer uyijianZong2) {
        this.uyijianZong2 = uyijianZong2;
    }

    public Double getUyijianDouble() {
        return uyijianDouble;
    }

    public void setUyijianDouble(Double uyijianDouble) {
        this.uyijianDouble = uyijianDouble;
    }

    public Double getUyijianDouble1() {
        return uyijianDouble1;
    }

    public void setUyijianDouble1(Double uyijianDouble1) {
        this.uyijianDouble1 = uyijianDouble1;
    }

    public Double getUyijianDouble2() {
        return uyijianDouble2;
    }

    public void setUyijianDouble2(Double uyijianDouble2) {
        this.uyijianDouble2 = uyijianDouble2;
    }

    public Integer getUyijianType() {
        return uyijianType;
    }

    public void setUyijianType(Integer uyijianType) {
        this.uyijianType = uyijianType;
    }

    public Integer getUyijianType1() {
        return uyijianType1;
    }

    public void setUyijianType1(Integer uyijianType1) {
        this.uyijianType1 = uyijianType1;
    }

    public Integer getUyijianType2() {
        return uyijianType2;
    }

    public void setUyijianType2(Integer uyijianType2) {
        this.uyijianType2 = uyijianType2;
    }

    public Integer getUxtypeId() {
        return uxtypeId;
    }

    public void setUxtypeId(Integer uxtypeId) {
        this.uxtypeId = uxtypeId;
    }

    public String getUxtypeName() {
        return uxtypeName;
    }

    public void setUxtypeName(String uxtypeName) {
        this.uxtypeName = uxtypeName == null ? null : uxtypeName.trim();
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    public Integer getBumenId() {
        return bumenId;
    }

    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    public String getBumenName() {
        return bumenName;
    }

    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    public Integer getBuyuanId() {
        return buyuanId;
    }

    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    public String getBuyuanName() {
        return buyuanName;
    }

    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    public Integer getBuzhiId() {
        return buzhiId;
    }

    public void setBuzhiId(Integer buzhiId) {
        this.buzhiId = buzhiId;
    }

    public String getBuzhiName() {
        return buzhiName;
    }

    public void setBuzhiName(String buzhiName) {
        this.buzhiName = buzhiName == null ? null : buzhiName.trim();
    }

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }
}