package com.model;

import java.util.Date;

public class Yonghu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuId
     *
     * @mbggenerated
     */
    private Integer yonghuId;

    private String yonghuName;

    private String yonghuPassword;

    private String yonghuXingming;

    private Integer yonghuSex;

    private Integer yonghuAge;

    private String yonghuPhone;

    private String yonghuMinzu;

    private String yonghuMark;

    private String yonghuMark1;

    private String yonghuMark2;

    private String yonghuMark3;

    private String yonghuMark4;

    private Date yonghuDate;

    private Date yonghuDate1;

    private Date yonghuDate2;

    private Integer yonghuType;

    private Integer yonghuType1;

    private Integer yonghuType2;

    private Double yonghuDouble;

    private Double yonghuDouble1;

    private Double yonghuDouble2;

    private Integer yonghuZong;

    private Integer yonghuZong1;

    private Integer yonghuZong2;

    private String yonghuImg;

    private String yonghuImgName;

    private Integer yhroleId;

    private String yhroleName;

    private Integer byuzhiId;

    private String byuzhiName;

    private Integer byumenId;

    private String byumenName;

    private Integer byuyuanId;

    private String byuyuanName;

    private Integer userId;

    private String userName;

    private Integer bumenId;

    private String bumenName;

    private Integer buyuanId;

    private String buyuanName;

    private Integer buzhiId;

    private String buzhiName;

    public Integer getYonghuId() {
        return yonghuId;
    }

    public void setYonghuId(Integer yonghuId) {
        this.yonghuId = yonghuId;
    }

    public String getYonghuName() {
        return yonghuName;
    }

    public void setYonghuName(String yonghuName) {
        this.yonghuName = yonghuName == null ? null : yonghuName.trim();
    }

    public String getYonghuPassword() {
        return yonghuPassword;
    }

    public void setYonghuPassword(String yonghuPassword) {
        this.yonghuPassword = yonghuPassword == null ? null : yonghuPassword.trim();
    }

    public String getYonghuXingming() {
        return yonghuXingming;
    }

    public void setYonghuXingming(String yonghuXingming) {
        this.yonghuXingming = yonghuXingming == null ? null : yonghuXingming.trim();
    }

    public Integer getYonghuSex() {
        return yonghuSex;
    }

    public void setYonghuSex(Integer yonghuSex) {
        this.yonghuSex = yonghuSex;
    }

    public Integer getYonghuAge() {
        return yonghuAge;
    }

    public void setYonghuAge(Integer yonghuAge) {
        this.yonghuAge = yonghuAge;
    }

    public String getYonghuPhone() {
        return yonghuPhone;
    }

    public void setYonghuPhone(String yonghuPhone) {
        this.yonghuPhone = yonghuPhone == null ? null : yonghuPhone.trim();
    }

    public String getYonghuMinzu() {
        return yonghuMinzu;
    }

    public void setYonghuMinzu(String yonghuMinzu) {
        this.yonghuMinzu = yonghuMinzu == null ? null : yonghuMinzu.trim();
    }

    public String getYonghuMark() {
        return yonghuMark;
    }

    public void setYonghuMark(String yonghuMark) {
        this.yonghuMark = yonghuMark == null ? null : yonghuMark.trim();
    }

    public String getYonghuMark1() {
        return yonghuMark1;
    }

    public void setYonghuMark1(String yonghuMark1) {
        this.yonghuMark1 = yonghuMark1 == null ? null : yonghuMark1.trim();
    }

    public String getYonghuMark2() {
        return yonghuMark2;
    }

    public void setYonghuMark2(String yonghuMark2) {
        this.yonghuMark2 = yonghuMark2 == null ? null : yonghuMark2.trim();
    }

    public String getYonghuMark3() {
        return yonghuMark3;
    }

    public void setYonghuMark3(String yonghuMark3) {
        this.yonghuMark3 = yonghuMark3 == null ? null : yonghuMark3.trim();
    }

    public String getYonghuMark4() {
        return yonghuMark4;
    }

    public void setYonghuMark4(String yonghuMark4) {
        this.yonghuMark4 = yonghuMark4 == null ? null : yonghuMark4.trim();
    }

    public Date getYonghuDate() {
        return yonghuDate;
    }

    public void setYonghuDate(Date yonghuDate) {
        this.yonghuDate = yonghuDate;
    }

    public Date getYonghuDate1() {
        return yonghuDate1;
    }

    public void setYonghuDate1(Date yonghuDate1) {
        this.yonghuDate1 = yonghuDate1;
    }

    public Date getYonghuDate2() {
        return yonghuDate2;
    }

    public void setYonghuDate2(Date yonghuDate2) {
        this.yonghuDate2 = yonghuDate2;
    }

    public Integer getYonghuType() {
        return yonghuType;
    }

    public void setYonghuType(Integer yonghuType) {
        this.yonghuType = yonghuType;
    }

    public Integer getYonghuType1() {
        return yonghuType1;
    }

    public void setYonghuType1(Integer yonghuType1) {
        this.yonghuType1 = yonghuType1;
    }

    public Integer getYonghuType2() {
        return yonghuType2;
    }

    public void setYonghuType2(Integer yonghuType2) {
        this.yonghuType2 = yonghuType2;
    }

    public Double getYonghuDouble() {
        return yonghuDouble;
    }

    public void setYonghuDouble(Double yonghuDouble) {
        this.yonghuDouble = yonghuDouble;
    }

    public Double getYonghuDouble1() {
        return yonghuDouble1;
    }

    public void setYonghuDouble1(Double yonghuDouble1) {
        this.yonghuDouble1 = yonghuDouble1;
    }

    public Double getYonghuDouble2() {
        return yonghuDouble2;
    }

    public void setYonghuDouble2(Double yonghuDouble2) {
        this.yonghuDouble2 = yonghuDouble2;
    }

    public Integer getYonghuZong() {
        return yonghuZong;
    }

    public void setYonghuZong(Integer yonghuZong) {
        this.yonghuZong = yonghuZong;
    }

    public Integer getYonghuZong1() {
        return yonghuZong1;
    }

    public void setYonghuZong1(Integer yonghuZong1) {
        this.yonghuZong1 = yonghuZong1;
    }

    public Integer getYonghuZong2() {
        return yonghuZong2;
    }

    public void setYonghuZong2(Integer yonghuZong2) {
        this.yonghuZong2 = yonghuZong2;
    }

    public String getYonghuImg() {
        return yonghuImg;
    }

    public void setYonghuImg(String yonghuImg) {
        this.yonghuImg = yonghuImg == null ? null : yonghuImg.trim();
    }

    public String getYonghuImgName() {
        return yonghuImgName;
    }

    public void setYonghuImgName(String yonghuImgName) {
        this.yonghuImgName = yonghuImgName == null ? null : yonghuImgName.trim();
    }

    public Integer getYhroleId() {
        return yhroleId;
    }

    public void setYhroleId(Integer yhroleId) {
        this.yhroleId = yhroleId;
    }

    public String getYhroleName() {
        return yhroleName;
    }

    public void setYhroleName(String yhroleName) {
        this.yhroleName = yhroleName == null ? null : yhroleName.trim();
    }

    public Integer getByuzhiId() {
        return byuzhiId;
    }

    public void setByuzhiId(Integer byuzhiId) {
        this.byuzhiId = byuzhiId;
    }

    public String getByuzhiName() {
        return byuzhiName;
    }

    public void setByuzhiName(String byuzhiName) {
        this.byuzhiName = byuzhiName == null ? null : byuzhiName.trim();
    }

    public Integer getByumenId() {
        return byumenId;
    }

    public void setByumenId(Integer byumenId) {
        this.byumenId = byumenId;
    }

    public String getByumenName() {
        return byumenName;
    }

    public void setByumenName(String byumenName) {
        this.byumenName = byumenName == null ? null : byumenName.trim();
    }

    public Integer getByuyuanId() {
        return byuyuanId;
    }

    public void setByuyuanId(Integer byuyuanId) {
        this.byuyuanId = byuyuanId;
    }

    public String getByuyuanName() {
        return byuyuanName;
    }

    public void setByuyuanName(String byuyuanName) {
        this.byuyuanName = byuyuanName == null ? null : byuyuanName.trim();
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    public Integer getBumenId() {
        return bumenId;
    }

    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    public String getBumenName() {
        return bumenName;
    }

    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    public Integer getBuyuanId() {
        return buyuanId;
    }

    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    public String getBuyuanName() {
        return buyuanName;
    }

    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    public Integer getBuzhiId() {
        return buzhiId;
    }

    public void setBuzhiId(Integer buzhiId) {
        this.buzhiId = buzhiId;
    }

    public String getBuzhiName() {
        return buzhiName;
    }

    public void setBuzhiName(String buzhiName) {
        this.buzhiName = buzhiName == null ? null : buzhiName.trim();
    }
}